export const PUBLIC_TRACK_ORDER_RESPONSE_KEYS = [
  "publicToken",
  "productName",
  "quantity",
  "unitPrice",
  "shippingFee",
  "totalPrice",
  "orderTotal",
  "paymentLast5",
  "pickupMethod",
  "specValues",
  "status",
  "statusLabel",
  "shippingStatus",
  "shippingStatusLabel",
  "trackingCode",
  "trackingProvider",
  "trackingProviderLabel",
  "latestTrackingStatus",
  "latestTrackingStatusLabel",
  "latestTrackingTime",
  "shipmentUpdatedAt",
  "storeName",
  "recipientNameMasked",
  "recipientPhoneMasked",
  "recipientAddressMasked",
  // Every element is separately reduced to PUBLIC_CART_ITEM_RESPONSE_KEYS before exposure.
  "items",
  "createdAt",
] as const;
