import {Router} from 'express';
import {registerCatalog} from '../lib/catalogHttp.ts';
const router=Router();
registerCatalog(router,'get','/stores/:storeId/catalog-products','catalogList');
registerCatalog(router,'post','/stores/:storeId/catalog-products','catalogCreate');
registerCatalog(router,'get','/stores/:storeId/catalog-products/:catalogProductId','catalogGet');
registerCatalog(router,'patch','/stores/:storeId/catalog-products/:catalogProductId','catalogPatch');
registerCatalog(router,'delete','/stores/:storeId/catalog-products/:catalogProductId','catalogDelete');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/correct-barcode','catalogCorrectBarcode');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/clone-with-new-barcode','catalogClone');
registerCatalog(router,'get','/stores/:storeId/catalog-products/:catalogProductId/aliases','catalogAliases');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/aliases','catalogAliasCreate');
registerCatalog(router,'delete','/stores/:storeId/catalog-products/:catalogProductId/aliases/:aliasId','catalogAliasDelete');
registerCatalog(router,'get','/stores/:storeId/catalog-products/:catalogProductId/cost-records','catalogCosts');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/cost-records','catalogCostCreate');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/cost-records/:recordId/void','catalogCostVoid');
registerCatalog(router,'get','/stores/:storeId/catalog-products/:catalogProductId/shopee-prices','catalogShopee');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/shopee-prices','catalogShopeeCreate');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/shopee-prices/:recordId/void','catalogShopeeVoid');
registerCatalog(router,'get','/stores/:storeId/catalog-products/:catalogProductId/relationships','catalogRelationships');
registerCatalog(router,'post','/stores/:storeId/catalog-products/:catalogProductId/relationships','catalogRelationshipCreate');
registerCatalog(router,'delete','/stores/:storeId/catalog-products/:catalogProductId/relationships/:relationshipId','catalogRelationshipDelete');
registerCatalog(router,'get','/stores/:storeId/catalog-products/:catalogProductId/audit','catalogAudit');
export default router;
