import {test,expect} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {installClerkStub} from './clerkStub.mjs';
const f=JSON.parse(process.env.PIKA_PHASE6_FIXTURES),s=f.store,evidence=process.env.PIKA_PHASE6_BROWSER_EVIDENCE;
const api=async(page,method,path,data,status=200)=>{const r=await page.request.fetch('/api'+path,{method,headers:{Authorization:'Bearer e2e-owner-token'},data});const v=await r.json();expect(r.status(),JSON.stringify(v)).toBe(status);return v;};
test.beforeEach(async({page})=>{await installClerkStub(page,{signedIn:true,userId:f.owner});await page.addInitScript(()=>{Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async value=>{window.__phase6Message=value;}}});});});
for(const width of [390,1440])test(`mixed create, actual pending capture, edit, complete, stats, receipt and public privacy ${width}`,async({page})=>{
 await page.setViewportSize({width,height:900});await api(page,'PATCH',`/stores/${s}`,{purchaseExchangeRate:1});await api(page,'POST',`/stores/${s}/pricing-settings/initialize`,{});await api(page,'PATCH',`/stores/${s}/pricing-settings`,{lossProtectionTwd:'0',purchasePaymentFeeRate:'0',routePaymentFeeRate:'0'});
 const ship=(await api(page,'POST',`/stores/${s}/shipping-profiles`,{name:`瀏覽器零運費 ${width}`,code:`BROWSER_${width}`,rateTwd:'0',basisWeightGrams:'1000'})).record.id;
 const make=async(name,cost)=>(await api(page,'POST',`/stores/${s}/catalog-products`,{name,barcode:'0',barcodeStatus:'NONE',weightGrams:'1',originalPriceJpy:String(cost),defaultShippingProfileId:ship})).product;
 const a=await make(`瀏覽器 A ${width}`,70),b=await make(`瀏覽器 B ${width}`,40);
 await page.goto(`/product-database/${a.id}`);await page.getByRole('button',{name:'加入訂單',exact:true}).click();
 const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'新增訂單',exact:true})).toBeVisible();await dialog.getByLabel('品項 1 單價',{exact:true}).fill('100');await dialog.getByLabel('品項 1 數量',{exact:true}).fill('2');
 await dialog.getByLabel('搜尋資料庫商品',{exact:true}).fill(b.name);await dialog.getByRole('button',{name:`加入 ${b.name}`,exact:true}).click();await dialog.getByLabel('品項 2 單價',{exact:true}).fill('50');await dialog.getByLabel('品項 2 數量',{exact:true}).fill('3');
 for(const index of [0,1]){const card=dialog.getByRole('article').nth(index);await card.locator('summary').click();await card.getByRole('checkbox',{name:'明確免攤交通（仍須完整其他成本）'}).check();await card.getByLabel(`品項 ${index+1} 配送溫層`,{exact:true}).selectOption('常溫');}
 await dialog.getByRole('button',{name:'加入一次性品項',exact:true}).click();await dialog.getByLabel('品項 3 品名',{exact:true}).fill(`瀏覽器一次性 ${width}`);await dialog.getByLabel('品項 3 單價',{exact:true}).fill('20');await dialog.getByLabel('品項 3 配送溫層',{exact:true}).selectOption('常溫');
 await dialog.getByPlaceholder('請輸入買家姓名',{exact:true}).fill('瀏覽器混單');await dialog.getByPlaceholder('請輸入電話',{exact:true}).fill('0912345678');await dialog.getByRole('button',{name:/面交 \/ 自取/}).click();
 const savedResponse=page.waitForResponse(r=>r.url().endsWith(`/stores/${s}/catalog-orders`)&&r.request().method()==='POST');await dialog.getByRole('button',{name:'建立訂單',exact:true}).click();const response=await savedResponse;const order=await response.json();expect(response.status(),JSON.stringify(order)).toBe(201);expect(Number(order.totalPrice)).toBe(370);expect(order.quantity).toBe(6);expect(order.orderItems[2].profitSnapshotStatus).toBe('PENDING');expect(order.productId).toBeNull();await expect(dialog).toHaveCount(0);
 await page.goto('/orders');await page.getByPlaceholder('搜尋姓名、電話、訂單編號').fill(String(order.id));await page.getByText(`#${order.id}`,{exact:true}).first().click();await expect(page.getByRole('button',{name:`補齊成本 · 瀏覽器一次性 ${width}`,exact:true})).toBeVisible();
 const rejected=page.waitForResponse(r=>r.url().endsWith(`/orders/${order.id}/status`));await page.getByRole('button',{name:'已完成',exact:true}).last().click();expect((await rejected).status()).toBe(422);
 await page.getByRole('button',{name:`補齊成本 · 瀏覽器一次性 ${width}`,exact:true}).click();const costPanel=page.getByRole('region',{name:'品項成本快照'});await costPanel.getByLabel('日本原價 ¥',{exact:true}).fill('5');await costPanel.getByLabel('有效進貨成本 ¥',{exact:true}).fill('5');await costPanel.getByLabel('重量 g',{exact:true}).fill('1');await costPanel.getByLabel('國際航運',{exact:true}).selectOption(String(ship));await costPanel.getByRole('checkbox',{name:'明確免攤交通（仍須完整其他成本）'}).check();await costPanel.getByRole('button',{name:'確認捕捉成本',exact:true}).click();await expect(costPanel).toContainText('265.000000000000');await expect(costPanel).toContainText('105.000000000000');await page.screenshot({path:`${evidence}/mixed-cost-${width}.png`,fullPage:true});
 await page.getByRole('button',{name:'編輯訂單',exact:true}).click();const edit=page.getByRole('dialog');await expect(edit).toContainText(`瀏覽器一次性 ${width}`);await expect(edit).not.toContainText('2220');const updated=page.waitForResponse(r=>r.url().endsWith(`/orders/${order.id}`)&&r.request().method()==='PATCH');await edit.getByRole('button',{name:'儲存變更',exact:true}).click();const editResponse=await updated;expect(editResponse.status(),await editResponse.text()).toBe(200);await expect(edit).toHaveCount(0);
 await page.getByRole('button',{name:'訂單確認',exact:true}).click();const message=await page.evaluate(()=>window.__phase6Message);expect(message).toContain('370');expect(message).toContain(`瀏覽器一次性 ${width}`);expect(message).not.toMatch(/265|105|成本|匯率|利潤/);writeFileSync(`${evidence}/message-${width}.txt`,message);
 await page.evaluate(()=>Object.defineProperty(navigator,'userAgent',{configurable:true,get:()=> 'Android Chrome'}));const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'列印銷貨單',exact:true}).click();const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');const stored=await page.evaluate(()=>Object.keys(localStorage).filter(k=>k.startsWith('pickbee-receipt-preview:')).map(k=>JSON.parse(localStorage.getItem(k))).at(-1));expect(stored.html).toContain(`瀏覽器一次性 ${width}`);expect(stored.html).toContain('370');expect(stored.html).not.toContain('2220');expect(stored.html).not.toMatch(/totalCostTwd|unitProfit|exchangeRate|captureContext|internalNote/);writeFileSync(`${evidence}/receipt-${width}.html`,stored.html);await popup.screenshot({path:`${evidence}/receipt-${width}.png`,fullPage:true});await popup.close();
 await page.getByRole('button',{name:'已完成',exact:true}).last().click();await expect.poll(async()=>{const orders=await api(page,'GET',`/stores/${s}/orders`);return orders.find(o=>o.id===order.id)?.status;}).toBe('completed');
 await page.goto(`/product-database/${a.id}`);await page.getByRole('button',{name:'一般成交',exact:true}).click();await expect(page.getByRole('region',{name:'一般成交'}).last()).toContainText('成交件數');await page.screenshot({path:`${evidence}/formal-sales-${width}.png`,fullPage:true});
 const publicOrder=await api(page,'GET',`/orders/track/${order.publicToken}`);expect(publicOrder.items.length).toBe(3);expect(publicOrder.totalPrice).toBe(370);expect(JSON.stringify(publicOrder)).not.toMatch(/cost|profit|exchange|actor|customerTier|captureContext/i);
 await page.goto(`/track/${order.publicToken}`);await expect(page.getByText(`瀏覽器一次性 ${width}`,{exact:true})).toBeVisible();await expect(page.locator('body')).not.toContainText('2220');await page.screenshot({path:`${evidence}/public-track-${width}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
});
test('formal VIP provenance, delayed response preserves manual input, stale setting persists',async({page})=>{
 await page.setViewportSize({width:390,height:900});const settings=await api(page,'GET',`/stores/${s}/pricing-settings`),ship=settings.shippingProfiles.find(x=>x.code==='BROWSER_390').id;
 const cat=(await api(page,'POST',`/stores/${s}/catalog-products`,{name:'正式VIP瀏覽器樣本',barcode:'0',barcodeStatus:'NONE',weightGrams:'1',originalPriceJpy:'70',defaultShippingProfileId:ship})).product;
 const customer=await api(page,'POST',`/stores/${s}/customers`,{name:'瀏覽器VIP',code:'P6-BROWSER-VIP',tier:'vip'},201);
 const order=await api(page,'POST',`/stores/${s}/catalog-orders`,{buyerName:'瀏覽器VIP',buyerPhone:'0912345678',pickupMethod:'自取',customerId:customer.id,items:[{catalogProductId:cat.id,quantity:4,unitPriceTwd:'150',cost:{isTransportCostExempt:true}}]},201);await api(page,'PATCH',`/orders/${order.id}/status`,{status:'completed'});
 await page.goto(`/products/new?catalogId=${cat.id}`);await expect(page.getByText(/VIP 來源：最近正式 VIP 成交/)).toBeVisible();await expect(page.getByLabel('VIP 售價',{exact:true})).toHaveValue('150.00');await page.getByLabel('一般售價',{exact:true}).fill('200');await expect(page.getByLabel('VIP 售價',{exact:true})).toHaveValue('150.00');
 await page.getByLabel('VIP 售價',{exact:true}).fill('145');await page.getByLabel('一般售價',{exact:true}).fill('210');await expect(page.getByLabel('VIP 售價',{exact:true})).toHaveValue('145');await expect(page.getByText(/VIP 來源：手動輸入/)).toBeVisible();await page.screenshot({path:`${evidence}/vip-manual-390.png`,fullPage:true});
 await page.getByRole('button',{name:'VIP 重新跟隨一般售價',exact:true}).click();await expect(page.getByLabel('VIP 售價',{exact:true})).toHaveValue('210');
 let release,seenResolve,doneResolve,claimed=false;const gate=new Promise(r=>{release=r;}),seen=new Promise(r=>{seenResolve=r;}),done=new Promise(r=>{doneResolve=r;});const pattern='**/api/stores/*/catalog-sales?ids='+cat.id;
 const handler=async route=>{if(claimed)return route.fallback();claimed=true;const response=await route.fetch();seenResolve();await gate;try{await route.fulfill({response});}finally{doneResolve();}};await page.route(pattern,handler);
 try{await page.reload({waitUntil:'domcontentloaded'});await seen;await page.getByLabel('VIP 售價',{exact:true}).fill('143');release();await done;await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await expect(page.getByLabel('VIP 售價',{exact:true})).toHaveValue('143');await expect(page.getByText(/VIP 來源：手動輸入/)).toBeVisible();await page.screenshot({path:`${evidence}/vip-delayed-manual-390.png`,fullPage:true});}finally{release();await page.unroute(pattern,handler);}
 await page.goto('/product-database');await page.getByRole('button',{name:'計價設定',exact:true}).click();await page.getByRole('button',{name:'設定成交過期天數',exact:true}).click();const dialog=page.getByRole('dialog').last();await dialog.getByLabel('成交過期天數',{exact:true}).fill('181');await dialog.getByRole('button',{name:'確認儲存',exact:true}).click();await expect(page.getByText('目前 181 天；沒有可靠成交日期時顯示未知。',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'計價設定',exact:true}).click();await expect(page.getByText('目前 181 天；沒有可靠成交日期時顯示未知。',{exact:true})).toBeVisible();await page.screenshot({path:`${evidence}/stale-setting-390.png`,fullPage:true});expect((await api(page,'GET',`/stores/${s}/pricing-settings`)).settings.staleSaleDays).toBe(181);
});
