import {test,expect} from '@playwright/test';
import {writeFileSync,mkdirSync,readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {installClerkStub} from './clerkStub.mjs';
const fixture=JSON.parse(process.env.PIKA_PHASE4_FIXTURES), evidence=process.env.PIKA_PHASE4_EVIDENCE;
const headers={Authorization:'Bearer e2e-owner-token'};
test('focus revision: reproduce independent return and obscured cases',async({page})=>{
 const results=[];await page.goto('/product-database');await button(page,'計價設定').click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 results.push(await page.evaluate(()=>({name:'settings return',pass:document.activeElement.textContent==='計價設定',actual:document.activeElement.tagName})));
 const data=await (await page.request.get(`/api/stores/${fixture.store}/catalog-products?pageSize=1`,{headers})).json();await page.goto(`/product-database/${data.items[0].id}`);await button(page,'追加成本').click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog').waitFor({state:'hidden'});
 results.push(await page.evaluate(()=>({name:'cost return',pass:document.activeElement.textContent==='追加成本',actual:document.activeElement.tagName})));
 await page.setViewportSize({width:390,height:400});await page.goto('/product-database/new');await expect(button(page,'新增商品')).toBeEnabled();await page.getByLabel('內部備註',{exact:true}).focus();await page.keyboard.press('Tab');
 results.push(await page.evaluate(()=>{const e=document.activeElement,r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {name:'short viewport CTA',pass:e.textContent==='新增商品'&&e.contains(hit),active:e.textContent,rect:r.toJSON(),hit:hit?.outerHTML};}));
 await page.screenshot({path:`${evidence}/focus-short.png`});writeFileSync(`${evidence}/focus-results.json`,JSON.stringify(results,null,2));expect(results.filter(r=>!r.pass)).toEqual([]);
 if(process.env.PIKA_ORIGINAL_FOCUS_PROBE){const probe=process.env.PIKA_ORIGINAL_FOCUS_PROBE;expect(createHash('sha256').update(readFileSync(probe)).digest('hex').toUpperCase()).toBe('3FBB6CCFCC426A4C256064CA09531EC310588E84CD926479DF92FE57EE08E3B6');const out=evidence+'/original-probe';mkdirSync(out,{recursive:true});const {runFocusProbe}=await import(pathToFileURL(probe).href);const original=await runFocusProbe(page,new URL(page.url()).origin,new URL(`/product-database/${data.items[0].id}`,page.url()).href,out);expect(original.filter(r=>!r.pass)).toEqual([]);}
});
test('all three routes reflow with usable controls across five viewport widths',async({page})=>{
 // r2 trace completed 15 navigations and 20 readiness assertions before the final control read.
 // Controller-authorized aggregate budget for 5 widths x 3 routes; per-expect remains 15s.
 test.setTimeout(180000);
 const data=await (await page.request.get(`/api/stores/${fixture.store}/catalog-products?pageSize=1`,{headers})).json(),id=data.items[0].id;
 for(const width of [390,768,1024,1440,320])for(const [slug,url,title] of [['list','/product-database','商品資料庫'],['new','/product-database/new','新增至商品資料庫'],['detail',`/product-database/${id}`,data.items[0].name]]){
  await page.setViewportSize({width,height:900});await page.goto(url);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible();if(slug==='list')await expect(page.locator('article').first()).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const targets=await page.locator('main button:not(:disabled),main input,main select,main a').evaluateAll(nodes=>nodes.filter(n=>n.getBoundingClientRect().height>0).map(n=>({text:n.textContent||n.id,width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));expect(targets.filter(t=>t.width<44||t.height<44)).toEqual([]);
  await page.screenshot({path:`${evidence}/${slug}-viewport-${width}.png`});
 }
});
test('permission errors remain actionable and a different store has no prior store products',async({page})=>{
 const denied='**/api/stores/*/catalog-products*';await page.route(denied,route=>route.continue({headers:{...route.request().headers(),authorization:'Bearer e2e-other-token'}}));await page.goto('/product-database');await expect(page.getByRole('alert').filter({hasText:'存取權限'})).toBeVisible();await expect(page.getByText('尚無符合條件的商品',{exact:true})).not.toBeVisible();await page.unroute(denied);await button(page,'重試').click();await expect(page.locator('article').first()).toBeVisible();
 await page.route('**/api/**',route=>route.continue({headers:{...route.request().headers(),authorization:'Bearer e2e-other-token'}}));await page.reload();await expect(page.getByRole('heading',{name:'外店專用商品',exact:true})).toBeVisible();await expect(page.getByText('共 1 筆商品',{exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:/分頁商品/})).toHaveCount(0);
});
test.beforeEach(async({page})=>{await installClerkStub(page,{signedIn:true,userId:fixture.owner});});
const button=(page,name)=>page.getByRole('button',{name,exact:true});
async function confirm(page){await page.getByRole('dialog').last().getByRole('button',{name:'確認儲存',exact:true}).click();await expect(page.getByRole('dialog').last()).not.toBeVisible();}
async function create(page,name,barcode='0') {await page.goto('/product-database/new');await expect(button(page,'新增商品')).toBeEnabled();await page.getByLabel('商品名稱 *',{exact:true}).fill(name);await page.getByLabel('條碼狀態 *').selectOption(barcode==='0'?'NONE':'REAL');if(barcode!=='0')await page.getByLabel('條碼 *',{exact:true}).fill(barcode);await page.getByLabel('重量 g *').fill('15.25');await page.getByLabel('日本原始售價 ¥ *').fill('100');}
test('real Catalog browser CRUD, history, fee inheritance, pagination and responsive layout',async({page})=>{
 // Independent trace reached its final edit after ~119s of successful multi-page work.
 // Keep every operation/assertion and its 15s readiness limit; bound only this long case.
 test.setTimeout(180000);
 const errors=[],consoleMessages=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleMessages.push(m.text());});
 try{
 await page.goto('/product-database');await expect(page.getByRole('heading',{name:'商品資料庫',exact:true})).toBeVisible();
 await page.getByLabel('分類',{exact:true}).selectOption(String(fixture.category));await expect(page.getByText('共 14 筆商品',{exact:true})).toBeVisible();await expect(page.locator('article')).toHaveCount(12);await button(page,'下一頁').click();await expect(page.locator('article')).toHaveCount(2);await button(page,'清除').click();await expect(page.getByText('第 1 頁')).toBeVisible();
 const draft=await (await page.request.get(`/api/stores/${fixture.store}/pricing-settings`,{headers})).json();expect(draft.templates).toHaveLength(0);await button(page,'計價設定').click();await button(page,'明確建立系統預設').click();await expect(button(page,'新增自訂範本')).toBeVisible();await page.keyboard.press('Escape');
 await page.goto('/product-database/new');await button(page,'新增商品').click();await expect(page.getByRole('alert').first()).toBeFocused();
 await create(page,'費率測試');const options=await page.locator('#template option').allTextContents();expect(options.length).toBeGreaterThan(3);
 const perfume=page.locator('#template option').filter({hasText:'PERFUME'});const perfumeId=await perfume.getAttribute('value');await page.locator('#template').selectOption(perfumeId);await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue('');await button(page,'新增商品').click();await expect(page.getByRole('heading',{name:'費率測試',exact:true})).toBeVisible();const productUrl=page.url();
 await page.getByRole('link',{name:'編輯基本資料',exact:true}).click();await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue('');const generalId=await page.locator('#template option').filter({hasText:'GENERAL'}).first().getAttribute('value');await page.locator('#template').selectOption(generalId);await button(page,'儲存基本資料').click();await page.getByRole('link',{name:'編輯基本資料',exact:true}).click();await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue('');await page.getByLabel('百貨手續費率（留白依範本）').fill('0.02');await button(page,'儲存基本資料').click();await page.getByRole('link',{name:'編輯基本資料',exact:true}).click();await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue(/^0\.020*$/);await page.locator('#template').selectOption(perfumeId);await button(page,'儲存基本資料').click();await page.getByRole('link',{name:'編輯基本資料',exact:true}).click();await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue(/^0\.020*$/);await page.getByLabel('百貨手續費率（留白依範本）').fill('');await page.getByLabel('商品名稱 *',{exact:true}).fill('費率改名');await button(page,'儲存基本資料').click();await expect(page.getByText('費率測試 · 改名前名稱')).toBeVisible();
 await button(page,'追加成本').click();await page.getByLabel('日本原始售價 ¥',{exact:true}).fill('200');await page.getByLabel('觀察日期',{exact:true}).fill('2026-09-14');await confirm(page);await expect(page.getByText('● 目前成本',{exact:true})).toBeVisible();await page.getByRole('button',{name:/作廢成本 #/}).first().click();await page.getByLabel('原因',{exact:true}).selectOption('OTHER');await page.getByRole('dialog').getByRole('button',{name:'確認儲存'}).click();await expect(page.getByRole('alert').first()).toBeVisible();await page.getByLabel('原因說明（其他必填）').fill('瀏覽器測試作廢');await confirm(page);await expect(page.getByText(/作廢原因：瀏覽器測試作廢/)).toBeVisible();
 await button(page,'蝦皮參考').click();await button(page,'新增蝦皮參考').click();await page.getByLabel('參考價 NT$',{exact:true}).fill('333.25');await page.getByLabel('觀察日期',{exact:true}).fill('2026-09-14');await confirm(page);await expect(page.getByText(/2026-09-14 · 有效/)).toBeVisible();
 await button(page,'封存商品').click();await confirm(page);await expect(button(page,'還原商品')).toBeVisible();await button(page,'還原商品').click();await confirm(page);
 await page.goto('/product-database');await button(page,'計價設定').click();await button(page,'編輯PERFUME').click();await page.getByRole('dialog').last().getByLabel('百貨手續費率',{exact:true}).fill('0.025');await page.getByRole('dialog').last().getByRole('button',{name:'確認儲存'}).click();await expect(page.getByRole('dialog')).toHaveCount(1);await page.keyboard.press('Escape');await page.goto(productUrl+'/edit');await expect(page.getByText(/留白時依範本，目前為 0.025/)).toBeVisible();await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue('');
 for(const width of [390,768,1024,1440,320]){await page.setViewportSize({width,height:900});await page.goto('/product-database');await expect(page.getByRole('heading',{name:'商品資料庫',exact:true})).toBeVisible();await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);const targets=await page.getByRole('navigation',{name:'主要導覽'}).getByRole('button').evaluateAll(nodes=>nodes.map(n=>({width:n.getBoundingClientRect().width,height:n.getBoundingClientRect().height})));expect(targets).toHaveLength(5);expect(targets.every(t=>t.width>=44&&t.height>=44)).toBe(true);await page.screenshot({path:`${evidence}/catalog-${width}.png`,fullPage:true});}
 await page.setViewportSize({width:390,height:844});await page.goto(productUrl+'/edit');await expect(page.getByLabel('百貨手續費率（留白依範本）')).toHaveValue('');await page.screenshot({path:`${evidence}/catalog-edit-390.png`,fullPage:true});await page.goto(productUrl);await expect(page.getByRole('heading',{name:'費率改名',exact:true})).toBeVisible();await page.screenshot({path:`${evidence}/catalog-detail-390.png`,fullPage:true});expect(errors).toEqual([]);
 }finally{writeFileSync(`${evidence}/browser-errors.json`,JSON.stringify({errors,consoleMessages},null,2));}
});
test('focus revision: nested save cancel close and short viewport keyboard paths',async({page})=>{
 const observations=[];let releaseSettings;
 const focused=async(locator,label)=>{await expect(locator).toBeFocused();await expect.poll(()=>locator.evaluate(e=>{const r=e.getBoundingClientRect();return e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);observations.push({label,...await locator.evaluate(e=>({active:document.activeElement.tagName,text:document.activeElement.textContent,rect:e.getBoundingClientRect().toJSON()}))});};
 try{
 await page.goto('/product-database');await button(page,'計價設定').click();await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await focused(button(page,'計價設定'),'settings close button');
 await button(page,'計價設定').click();if(await button(page,'編輯PERFUME').count()===0)await button(page,'明確建立系統預設').click();const inner=button(page,'編輯PERFUME');await inner.click();await page.getByRole('dialog').last().getByRole('button',{name:'取消',exact:true}).click();await focused(inner,'nested cancel');
 await inner.click();await page.keyboard.press('Escape');await focused(inner,'nested Escape');await inner.click();await page.getByRole('dialog').last().getByRole('button',{name:'確認儲存',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(1);await focused(inner,'nested successful save after query refresh');await page.keyboard.press('Escape');await focused(button(page,'計價設定'),'outer Escape after nested save');
 const data=await (await page.request.get(`/api/stores/${fixture.store}/catalog-products?pageSize=1`,{headers})).json();await page.goto(`/product-database/${data.items[0].id}`);await button(page,'追加成本').click();await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();await focused(button(page,'追加成本'),'cost cancel');await button(page,'追加成本').click();await page.getByLabel('日本原始售價 ¥',{exact:true}).fill('200');await confirm(page);await focused(button(page,'追加成本'),'cost successful save after query refresh');
 await create(page,'焦點同碼取消','88000000');await button(page,'新增商品').click();await page.getByRole('dialog',{name:'此條碼已有商品'}).waitFor();await button(page,'返回檢查').click();await focused(button(page,'新增商品'),'duplicate cancel');await expect(page.getByLabel('商品名稱 *',{exact:true})).toHaveValue('焦點同碼取消');await page.keyboard.press('Enter');await page.getByRole('dialog',{name:'此條碼已有商品'}).waitFor();await page.keyboard.press('Escape');await focused(button(page,'新增商品'),'duplicate Escape');
 await page.setViewportSize({width:390,height:400});let heldSettingsResponse=false;const gate=new Promise(resolve=>{releaseSettings=resolve;});const settingsUrl=`**/api/stores/${fixture.store}/pricing-settings`;const holdSettings=async route=>{const response=await route.fetch();heldSettingsResponse=true;await gate;await route.fulfill({response});};await page.route(settingsUrl,holdSettings);await page.goto('/product-database/new');await expect.poll(()=>heldSettingsResponse).toBe(true);await expect(button(page,'新增商品')).toBeDisabled();const note=page.getByLabel('內部備註',{exact:true});await note.fill('保留的備註');await note.focus();await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'取消',exact:true})).toBeFocused();writeFileSync(`${evidence}/loading-boundary.json`,JSON.stringify({pendingDisabled:await button(page,'新增商品').isDisabled(),pendingActive:await page.evaluate(()=>document.activeElement.textContent),realSettingsResponseHeld:true},null,2));await page.screenshot({path:`${evidence}/loading-disabled.png`});releaseSettings();await expect(button(page,'新增商品')).toBeEnabled();await page.unroute(settingsUrl,holdSettings);await note.focus();await page.keyboard.press('Tab');await focused(button(page,'新增商品'),'short viewport forward Tab');await page.keyboard.press('Shift+Tab');await focused(note,'short viewport reverse Tab');await page.keyboard.press('Tab');await page.keyboard.press('Enter');await expect(page.getByRole('alert').first()).toBeFocused();await page.getByRole('alert').first().getByRole('link').first().click();await focused(page.getByLabel('商品名稱 *',{exact:true}),'error summary link reveals field');await expect(note).toHaveValue('保留的備註');await page.screenshot({path:`${evidence}/focus-error-link-short.png`});
 await page.setViewportSize({width:390,height:844});await expect(button(page,'新增商品')).toBeEnabled();await note.focus();await page.keyboard.press('Tab');await focused(button(page,'新增商品'),'normal viewport Tab');
 }finally{releaseSettings?.();writeFileSync(`${evidence}/focus-matrix.json`,JSON.stringify(observations,null,2));}
});
test('NONE similarity searches all matching records and duplicate REAL requires explicit confirmation',async({page})=>{
 await create(page,'相似樣本');await page.getByLabel('重量 g *').fill('20.25');await page.getByLabel('日本原始售價 ¥ *').fill('123');await expect(page.getByRole('heading',{name:'找到 26 筆相似的無條碼商品'})).toBeVisible();
 await create(page,'同碼第一筆','001234500');await button(page,'新增商品').click();await expect(page.getByRole('heading',{name:'同碼第一筆',exact:true})).toBeVisible();const first=page.url();await create(page,'同碼第二筆','001234500');await button(page,'新增商品').click();await expect(page.getByRole('dialog',{name:'此條碼已有商品'})).toBeVisible();await expect(page.getByRole('dialog').getByRole('listitem').filter({hasText:'同碼第一筆'})).toBeVisible();await button(page,'確認另外建立').click();await expect(page.getByRole('heading',{name:'同碼第二筆',exact:true})).toBeVisible();expect(page.url()).not.toBe(first);await expect(page.getByText('001234500',{exact:true})).toBeVisible();
});
