import {test,expect} from '@playwright/test';import {createRequire} from 'node:module';import {writeFileSync} from 'node:fs';
import {installClerkStub} from './clerkStub.mjs';
const f=JSON.parse(process.env.PIKA_PHASE78_FIXTURES),e=process.env.PIKA_PHASE78_EVIDENCE,require=createRequire(new URL('../artifacts/api-server/package.json',import.meta.url)),ExcelJS=require('exceljs');
test.beforeEach(async({page})=>{await installClerkStub(page,{signedIn:true,userId:f.owner});});
for(const width of [390,1440])test('single worksheet actual review and controlled commit rollback '+width,async({page})=>{
 await page.setViewportSize({width,height:900});const errors=[],consoleErrors=[];page.on('pageerror',x=>errors.push(String(x)));page.on('console',x=>{if(x.type()==='error')consoleErrors.push(x.text());});
 const w=new ExcelJS.Workbook(),selected=w.addWorksheet('要匯入');selected.getCell('B1').value='0000'+width;selected.getCell('C1').value='來源商品'+width;selected.getCell('D1').value=1000;selected.getCell('E1').value={formula:'1/10',result:0.1};selected.getCell('F1').value=915;selected.getCell('W1').value=777;w.addWorksheet('不要匯入').getCell('C1').value='排除商品';const buffer=Buffer.from(await w.xlsx.writeBuffer());
 await page.goto('/product-database');await page.getByRole('link',{name:'單分頁匯入',exact:true}).click();await expect(page.getByRole('heading',{name:'單分頁匯入審核',exact:true})).toBeVisible();
 await page.getByLabel('XLSX 檔案',{exact:true}).setInputFiles({name:'review'+width+'.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer});await page.getByRole('button',{name:'讀取分頁',exact:true}).click();await expect(page.getByRole('status')).toContainText('已讀取分頁');
 await expect(page.getByLabel('本批唯一分頁')).toHaveValue('');await page.getByLabel('本批唯一分頁').selectOption('要匯入');await page.getByRole('button',{name:'建立單分頁預覽',exact:true}).click();const row=page.locator('article[data-row-number="1"]');await expect(row).toContainText('來源商品'+width);await expect(page.locator('article[data-row-number]')).toHaveCount(1);
 await row.getByLabel('第 1 列操作').selectOption('CREATE');await expect(row.getByLabel('條碼文字',{exact:true})).toHaveValue('0000'+width);await expect(row.getByLabel('重量 g',{exact:true})).toHaveValue('0.10');await row.getByRole('checkbox',{name:'已核對原价、有效成本、g 與條碼語意'}).check();await row.getByLabel('第 1 列審核理由').fill('人工確認來源原價和有效成本');await row.getByRole('button',{name:'保存第 1 列審核'}).click();await expect(row).toContainText('已人工審核');
 await page.getByLabel('確認匯率',{exact:true}).fill('0');await page.getByRole('button',{name:'保存確認匯率'}).click();await expect(page.getByRole('alert')).toContainText('匯率');await expect(page.getByLabel('確認匯率',{exact:true})).toHaveValue('0');await page.getByLabel('確認匯率',{exact:true}).fill('0.21');await page.getByRole('button',{name:'保存確認匯率'}).click();await expect(page.getByRole('alert')).toHaveCount(0);
 await page.getByRole('checkbox',{name:'確認本批審核結果'}).check();await page.getByRole('button',{name:'批准此審核版本'}).click();await expect(page.getByRole('heading',{name:/批次.*APPROVED/})).toBeVisible();
 const captured=[];for(const name of ['批准此審核版本','執行已批准批次','安全回復本批']){const box=await page.getByRole('button',{name,exact:true}).boundingBox();expect(box.width).toBeGreaterThanOrEqual(44);expect(box.height).toBeGreaterThanOrEqual(44);captured.push({name,...box});}
 await page.getByRole('checkbox',{name:'確認本批審核結果'}).focus();await page.keyboard.press('Tab');expect(await page.evaluate(()=>document.activeElement?.tagName)).toBe('BUTTON');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:e+'/review-approved-'+width+'.png',fullPage:true});
 await page.getByRole('checkbox',{name:'確認本批審核結果'}).check();await page.getByRole('button',{name:'執行已批准批次'}).click();await expect(page.getByRole('heading',{name:/批次.*COMMITTED/})).toBeVisible();await page.getByRole('checkbox',{name:'確認本批審核結果'}).check();await page.getByRole('button',{name:'安全回復本批'}).click();await expect(page.getByRole('heading',{name:/批次.*ROLLED_BACK/})).toBeVisible();await page.screenshot({path:e+'/review-rolled-back-'+width+'.png',fullPage:true});
 writeFileSync(e+'/ui-observations-'+width+'.json',JSON.stringify({width,targets:captured,errors,consoleErrors},null,2));expect(errors).toEqual([]);expect(consoleErrors.filter(x=>/DialogTitle|Description/.test(x))).toEqual([]);
});
for(const width of [390,1440])test('listing preview defaults and manual linking '+width,async({page})=>{
 const queries=[];page.on('response',response=>{const url=new URL(response.url());if(url.pathname.endsWith('/listing-matches/preview'))queries.push({page:url.searchParams.get('page'),status:response.status()});});
 await page.setViewportSize({width,height:900});await page.goto('/product-database/matches');await page.getByRole('button',{name:'載入配對預覽'}).click();const card=page.getByRole('article').filter({has:page.getByRole('heading',{name:'合成舊上架 '+width,exact:true})});await expect(card).toBeVisible();const checkbox=card.getByRole('checkbox');await expect(checkbox).not.toBeChecked();await expect(card).toContainText('0012345');await expect(card).toContainText('真實條碼 缺失');await checkbox.check();await card.getByLabel(/配對操作/).selectOption('LINK');await card.getByLabel(/目標商品 /).fill(String(f.catalogId));await page.getByRole('button',{name:'只處理人工選取列'}).click();await expect(card).toContainText('已連結 #'+f.catalogId);await expect(checkbox).not.toBeChecked();await expect(checkbox).toBeDisabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.screenshot({path:e+'/listing-linked-'+width+'.png',fullPage:true});
 expect(queries.length).toBeGreaterThan(0);expect(queries.every(x=>x.page==='1'&&x.status===200)).toBe(true);writeFileSync(e+'/listing-http-'+width+'.json',JSON.stringify(queries,null,2));
});
