import {useState,useRef,useCallback} from 'react';
import {useAuth} from '@clerk/react';
import {Link} from 'wouter';
import {Button} from '@/components/ui/button';
import {Shell,StoreGate,panel,control,action,Loading} from '@/components/product-database/shared';
import {trimCatalogWeightZeros} from '@/lib/productDatabase';
function useImportApi(){const {getToken}=useAuth();return useCallback(async(path:string,body?:any)=>{const token=await getToken(),form=body instanceof FormData;const response=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,...(!form&&body!==undefined?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:form?body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error+(data.details?.blockers?'：'+data.details.blockers.map((b:any)=>'列 '+b.rowId+' '+b.reason).join('；'):''));return data;},[getToken]);}
const seed=(c:any)=>({name:c?.name??'',barcode:c?.barcode??c?.listingBarcode??'',barcodeStatus:c?.barcodeStatus??'REAL',weightGrams:c?.weightGrams??'',originalPriceJpy:c?.originalPriceJpy??'',effectiveCostJpy:c?.effectiveCostJpy??'',status:c?.status??'NORMAL',preferredRouteLabel:c?.preferredRouteLabel??'',shopeePriceTwd:c?.shopeePriceTwd??'',confirmed:false,forceCreate:false});
function Values({value:v,onChange,id}:{value:any;onChange:(v:any)=>void;id:string}){const set=(k:string,value:any)=>onChange({...v,[k]:value});return <div className="grid min-w-0 gap-3 sm:grid-cols-2">
 {([['name','名稱'],['barcode','條碼文字'],['originalPriceJpy','日本原價 ¥'],['effectiveCostJpy','有效進貨成本 ¥'],['weightGrams','重量 g'],['preferredRouteLabel','偏好路線'],['shopeePriceTwd','蝦皮參考 NT$']] as const).map(([k,label])=><label key={k} className="min-w-0 space-y-1" htmlFor={id+k}><span>{label}</span><input id={id+k} className={control} value={v[k]} inputMode={['originalPriceJpy','effectiveCostJpy','weightGrams','shopeePriceTwd'].includes(k)?'decimal':undefined} onChange={e=>set(k,e.target.value)}/></label>)}
 <label className="space-y-1">條碼語意<select className={control} value={v.barcodeStatus} onChange={e=>onChange({...v,barcodeStatus:e.target.value,barcode:e.target.value==='NONE'?'0':''})}><option value="REAL">真實條碼</option><option value="NONE">人工確認無條碼</option></select></label>
 <label className="space-y-1">店鋪狀態<select className={control} value={v.status} onChange={e=>set('status',e.target.value)}><option value="NORMAL">正常</option><option value="DISCONTINUED">店鋪停售</option></select></label>
 <label className="flex min-h-11 items-center gap-3 sm:col-span-2"><input type="checkbox" checked={v.confirmed} onChange={e=>set('confirmed',e.target.checked)}/>已核對原价、有效成本、g 與條碼語意</label>
 <label className="flex min-h-11 items-center gap-3 sm:col-span-2"><input type="checkbox" checked={v.forceCreate} onChange={e=>set('forceCreate',e.target.checked)}/>同條碼存在時，仍明確建立獨立商品</label>
 </div>;}
const cleanValues=(v:any)=>Object.fromEntries(Object.entries(v).filter(([k,value])=>k!=='adjustmentMode'&&!(['preferredRouteLabel','shopeePriceTwd'].includes(k)&&(value===''||value==null))));
function ReviewRow({row,onSave,busy}:{row:any;onSave:(r:any)=>void;busy:boolean}){
 const [choice,setChoice]=useState(row.resolution?.action??''),[catalog,setCatalog]=useState(String(row.resolution?.catalogProductId??'')),[reason,setReason]=useState(row.resolution?.reason??''),[v,setV]=useState({...seed(row.candidate),...row.resolution?.values});
 const product=row.rowKind==='PRODUCT';
 return <article className={panel} data-row-number={row.sourceRowNumber}><h3 className="mb-2 break-words font-semibold">第 {row.sourceRowNumber} 列 · {row.candidate?.name||'空白／未辨識列'}</h3><p className="mb-2 text-sm text-secondary-foreground">{row.rowKind} · {row.matchStatus}{row.resolution?' · 已人工審核':' · 尚未審核'}</p>
 {row.warnings?.messages?.length>0&&<ul className="mb-3 list-inside list-disc text-sm text-accent">{row.warnings.messages.map((w:string,i:number)=><li key={i}>{w}</li>)}</ul>}
 <details className="mb-3"><summary className="min-h-11 cursor-pointer py-2 underline">原始儲存格、公式與 cached value</summary><pre className="max-h-80 overflow-y-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify(row.rawValues,null,2)}</pre></details>
 <div className="space-y-3"><label className="block">人工決定<select aria-label={'第 '+row.sourceRowNumber+' 列操作'} className={control} disabled={busy} value={choice} onChange={e=>setChoice(e.target.value)}><option value="">請逐列選擇</option>{product&&<><option value="LINK">連結已確認商品並追加來源成本</option><option value="CREATE">建立獨立商品</option></>}<option value="IGNORE">忽略並保留原因</option></select></label>
 {choice==='LINK'&&<label className="block">目標商品編號<select className={control} aria-label={'第 '+row.sourceRowNumber+' 列候選'} value={catalog} onChange={e=>setCatalog(e.target.value)}><option value="">請選擇候選</option>{row.candidates.map((c:any)=><option key={c.id} value={c.id}>#{c.id} {c.name} · {c.barcode}</option>)}</select><input className={control} aria-label={'第 '+row.sourceRowNumber+' 列商品編號'} inputMode="numeric" value={catalog} onChange={e=>setCatalog(e.target.value)}/></label>}
 {['LINK','CREATE'].includes(choice)&&<Values id={'row'+row.id} value={v} onChange={setV}/>}
 {choice&&<><label className="block">審核理由<input aria-label={'第 '+row.sourceRowNumber+' 列審核理由'} className={control} value={reason} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><Button className={action} disabled={busy||!reason.trim()||choice!=='IGNORE'&&!v.confirmed} onClick={()=>onSave({rowId:row.id,resolution:{action:choice,reason,...(choice==='LINK'?{catalogProductId:Number(catalog)}:{}),...(choice==='IGNORE'?{}:{values:cleanValues(v)})}})}>保存第 {row.sourceRowNumber} 列審核</Button></>}
 </div></article>;
}
function ImportPage({s}:{s:number}){
 const api=useImportApi(),[sourceType,setSourceType]=useState('XLSX_UPLOAD'),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[sheet,setSheet]=useState(''),[sheets,setSheets]=useState<string[]>([]),[cells,setCells]=useState('[]'),[data,setData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[fx,setFx]=useState(''),[page,setPage]=useState(1),[confirmation,setConfirmation]=useState(false);
 const run=async(work:()=>Promise<any>,notice:string)=>{setBusy(true);setError('');setMessage('');try{const value=await work();setMessage(notice);return value;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}};
 const payload=(selected:boolean)=>{if(sourceType==='STRUCTURED_CELLS')return {sourceType,spreadsheetTitle:title,sheetTitle:sheet,cells:JSON.parse(cells)};if(!file)throw Error('請先選擇 XLSX 檔案');const form=new FormData();form.append('sourceType','XLSX_UPLOAD');form.append('spreadsheetTitle',title||file.name);if(selected)form.append('sheetTitle',sheet);form.append('file',file);return form;};
 const endpoint='/stores/'+s+'/sheet-imports',terminal=data&&['COMMITTED','ROLLED_BACK','FAILED'].includes(data.batch.status);
 const mutate=async(actionName:string,body:any)=>{const value=await run(()=>api(endpoint+'/'+data.batch.id+'/'+actionName,body),'操作已保存');if(value){setData(value);if(body.exchangeRate!==undefined)setFx(value.batch.exchangeRateSnapshot??'');setConfirmation(false);}};
 return <Shell title="單分頁匯入審核"><p className="mb-5 text-secondary-foreground">上傳副本只證明該版本；即時 Google Sheet 是否更新尚未驗證。W／X／AC／AL 是舊參考價，永遠不算正式成交。</p>
 <section className={panel}><h2 className="mb-4 text-lg font-semibold">1. 選擇來源與一個分頁</h2><div className="space-y-3">
 <label className="block">來源方式<select aria-label="來源方式" className={control} value={sourceType} disabled={busy} onChange={e=>{setSourceType(e.target.value);setSheet('');setSheets([]);}}><option value="XLSX_UPLOAD">XLSX 上傳副本</option><option value="STRUCTURED_CELLS">明確結構化儲存格</option></select></label>
 {sourceType==='XLSX_UPLOAD'&&<><label className="block">XLSX 檔案（最多 2 MiB）<input aria-label="XLSX 檔案" className={control} type="file" accept=".xlsx" disabled={busy} onChange={e=>{const next=e.target.files?.[0]??null;setFile(next);setTitle(next?.name??'');setSheet('');setSheets([]);}}/></label><Button variant="outline" className={action} disabled={busy||!file} onClick={async()=>{const result=await run(()=>api(endpoint+'/preview',payload(false)),'已讀取分頁，尚未建立匯入批次');if(result)setSheets(result.sheetTitles);}}>讀取分頁</Button></>}
 <label className="block">檔案／試算表名稱<input className={control} aria-label="試算表名稱" value={title} onChange={e=>setTitle(e.target.value)}/></label>
 {sourceType==='XLSX_UPLOAD'?<label className="block">本批唯一分頁<select aria-label="本批唯一分頁" className={control} value={sheet} onChange={e=>setSheet(e.target.value)}><option value="">請人工選一個分頁</option>{sheets.map(n=><option key={n} value={n}>{n}</option>)}</select></label>:<><label className="block">分頁名稱<input className={control} aria-label="分頁名稱" value={sheet} onChange={e=>setSheet(e.target.value)}/></label><label className="block">儲存格 JSON<textarea className={control+' min-h-40 font-mono text-sm'} aria-label="儲存格 JSON" value={cells} onChange={e=>setCells(e.target.value)}/></label><p className="text-sm text-secondary-foreground">每格包含 row、column、type、value；公式另附 formula、cachedValue。B=2、C=3、D=4、E=5、F=6。原數字文字請使用字串。</p></>}
 <Button className={action} disabled={busy||!title||!sheet} onClick={async()=>{const value=await run(()=>api(endpoint+'/preview',payload(true)),'已建立預覽；尚未写入商品');if(value){setData(value);setPage(1);setFx(value.batch.exchangeRateSnapshot??'');setConfirmation(false);}}}>建立單分頁預覽</Button>
 </div></section>
 {error&&<div role="alert" className="my-4 break-words border border-destructive p-4">{error}</div>}{message&&<p role="status" className="my-4">{message}</p>}
 {data&&<><section className={panel+' my-5 space-y-3'}><h2 className="text-lg font-semibold">2. 批次 #{data.batch.id} · {data.batch.status}</h2><p>{data.batch.spreadsheetTitle} ／ {data.batch.sheetTitle} · 審核版本 {data.batch.reviewVersion}</p><dl className="space-y-2 text-xs"><div><dt>原始 XLSX bytes SHA256</dt><dd className="break-all">{data.batch.originalFileSha256??'此 STRUCTURED_CELLS 來源沒有原始 XLSX 證據'}</dd></div><div><dt>所選分頁 canonical SHA256</dt><dd className="break-all">{data.batch.sourceHash}</dd></div><div><dt>已批准審核計畫 SHA256</dt><dd className="break-all">{data.batch.approvalHash??'尚未批准'}</dd></div></dl></section>
 <div className="grid gap-4">{data.rows.slice((page-1)*10,page*10).map((row:any)=><ReviewRow key={data.batch.id+':'+row.id+':'+JSON.stringify(row.resolution)} row={row} busy={busy||terminal} onSave={resolution=>void mutate('resolve',{rows:[resolution]})}/>)}</div>
 <nav aria-label="匯入列分頁" className="my-4 flex flex-wrap items-center justify-between gap-3"><Button className={action} variant="outline" disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>上一頁</Button><span>第 {page} 頁 · {data.rows.length} 列</span><Button className={action} variant="outline" disabled={page*10>=data.rows.length||busy} onClick={()=>setPage(p=>p+1)}>下一頁</Button></nav>
 <section className={panel+' space-y-4'}><h2 className="text-lg font-semibold">3. 確認匯率與審核結果</h2><p>更改任何列或匯率會立即取消先前批准；必須重新審核。尚未審核 PRODUCT：{data.rows.filter((r:any)=>r.rowKind==='PRODUCT'&&!r.resolution).length}</p>
 <label className="block">人工確認的 JPY → TWD 匯率<input className={control} aria-label="確認匯率" inputMode="decimal" value={fx} disabled={busy||terminal} onChange={e=>setFx(e.target.value)}/></label><Button className={action} variant="outline" disabled={busy||terminal||!fx} onClick={()=>void mutate('resolve',{exchangeRate:fx})}>保存確認匯率</Button>
 <label className="flex min-h-11 items-center gap-3"><input type="checkbox" aria-label="確認本批審核結果" checked={confirmation} disabled={busy||data.batch.status==='ROLLED_BACK'} onChange={e=>setConfirmation(e.target.checked)}/>我已逐列確認此來源版本與操作結果</label>
 <div className="flex flex-wrap gap-3"><Button className={action} disabled={busy||terminal||!confirmation||fx!==String(data.batch.exchangeRateSnapshot??'')} onClick={()=>void mutate('approve',{confirmed:true,reviewVersion:data.batch.reviewVersion})}>批准此審核版本</Button><Button className={action} disabled={busy||data.batch.status!=='APPROVED'||!confirmation||fx!==String(data.batch.exchangeRateSnapshot??'')} onClick={()=>void mutate('commit',{confirmed:true})}>執行已批准批次</Button><Button variant="outline" className={action} disabled={busy||data.batch.status!=='COMMITTED'||!confirmation} onClick={()=>void mutate('rollback',{confirmed:true})}>安全回復本批</Button></div><p className="text-sm text-secondary-foreground">有後續引用時回復會被拒絕，歷史不會刪除。正式來源請停在批准前，僅本次合成測試可執行／回復。</p>
 {data.effects.length>0&&<ul className="space-y-2">{data.effects.map((v:any)=><li key={v.id} className="break-words">列 #{v.rowId} → <Link className="underline" href={'/product-database/'+v.catalogProductId}>商品 #{v.catalogProductId}</Link> · 成本 #{v.createdCostRecordId} · {v.createdCatalog?'本批新建':'既有商品'}</li>)}</ul>}</section></>}
 </Shell>;
}
function ListingCard({item,draft,onChange}:{item:any;draft:any;onChange:(v:any)=>void}){const v=draft??{selected:false,action:'',catalogProductId:'',values:seed({...item,weightGrams:typeof item.weightGrams==='string'?trimCatalogWeightZeros(item.weightGrams):item.weightGrams})};return <article className={panel+' space-y-3'}>
 <label className="flex min-h-11 items-center gap-3"><input type="checkbox" aria-label={'選擇 '+item.name} disabled={!!item.catalogProductId} checked={v.selected} onChange={e=>onChange({...v,selected:e.target.checked})}/><h2 className="break-words font-semibold">{item.name}</h2></label><p>{item.catalogProductId?'已連結 #'+item.catalogProductId:'尚未連結'} · Listing #{item.id}</p><dl className="space-y-1 text-sm"><div>一般 NT$ {item.price} ／ VIP {item.vipPrice??'未設定'}</div><div>原價 ¥ {item.originalPriceJpy??'缺失'} ／ 有效成本 ¥ {item.effectiveCostJpy??'缺失'}</div><div>重量 {item.weightGrams??'缺失'} g · {item.weightSource}</div><div>SKU {item.skuCode??'未設定'} ／ 真實條碼 {item.listingBarcode??'缺失'}</div><div>Route #{item.tripRouteId??'未設定'}</div><div>相關訂單 {item.relatedOrderCount} 筆（{item.orderCountLabel}）</div></dl>{item.suspectedTest&&<p className="text-accent">{item.testReason}</p>}{item.candidates.some((p:any)=>p.matchType==='CONFLICT')&&<p className="text-accent">配對衝突：同碼異名或同名異碼，請人工核對候選。</p>}{item.missing.length>0&&<p className="text-accent">待確認：{item.missing.join('、')}。legacy 成本不能冒充原價；kg 換算不恢復已丟精度。</p>}
 {v.selected&&<><label className="block">操作<select aria-label={'配對操作 '+item.id} className={control} value={v.action} onChange={e=>onChange({...v,action:e.target.value})}><option value="">請人工選擇</option><option value="LINK">連結已確認商品</option><option value="CREATE">人工補齊並建立新商品</option><option value="IGNORE">忽略</option></select></label>{v.action==='LINK'&&<label className="block">目標商品<select className={control} value={v.catalogProductId} onChange={e=>onChange({...v,catalogProductId:e.target.value})}><option value="">請選擇候選</option>{item.candidates.map((p:any)=><option value={p.id} key={p.id}>#{p.id} {p.name} · {p.barcode}</option>)}</select><input className={control} aria-label={'目標商品 '+item.id} value={v.catalogProductId} inputMode="numeric" onChange={e=>onChange({...v,catalogProductId:e.target.value})}/></label>}{v.action==='CREATE'&&<Values id={'listing'+item.id} value={v.values} onChange={values=>onChange({...v,values})}/>}</>}
 </article>;}
function MatchesPage({s}:{s:number}){
 const api=useImportApi(),[data,setData]=useState<any>(null),[page,setPage]=useState(1),[drafts,setDrafts]=useState<Record<string,any>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const request=useRef({serialized:'',key:''});
 const load=async(p:number)=>{setBusy(true);setError('');try{setData(await api('/stores/'+s+'/listing-matches/preview?page='+p));setPage(p);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <Shell title="既有上架商品配對"><p className="mb-5 text-secondary-foreground">全部預設不選。配對不改舊售價、成本與訂單快照；舊訂單不會追溯歸入新商品成交。</p><Button className={action+' mb-4'} disabled={busy} onClick={()=>void load(page)}>載入配對預覽</Button>{error&&<p role="alert" className="my-4 break-words text-destructive">{error}</p>}{message&&<p role="status" className="my-4">{message}</p>}{busy&&!data&&<Loading/>}
 <div className="grid gap-4 lg:grid-cols-2">{data?.items.map((item:any)=><ListingCard key={item.id} item={item} draft={drafts[item.id]} onChange={v=>setDrafts(d=>({...d,[item.id]:v}))}/>)}</div>{data&&<><nav aria-label="配對分頁" className="my-4 flex flex-wrap justify-between gap-3"><Button className={action} variant="outline" disabled={busy||page===1} onClick={()=>void load(page-1)}>上一頁</Button><span>第 {page} 頁 ／ {data.total} 筆</span><Button className={action} variant="outline" disabled={busy||page*25>=data.total} onClick={()=>void load(page+1)}>下一頁</Button></nav><Button className={action} disabled={busy||!Object.values(drafts).some(v=>v.selected)} onClick={async()=>{setBusy(true);setError('');try{const rows=Object.entries(drafts).filter(([,v])=>v.selected).map(([id,v])=>({productId:Number(id),action:v.action,...(v.action==='LINK'?{catalogProductId:Number(v.catalogProductId)}:{}),...(v.action==='CREATE'?{values:cleanValues(v.values)}:{})})),serialized=JSON.stringify(rows);if(serialized!==request.current.serialized)request.current={serialized,key:crypto.randomUUID()};await api('/stores/'+s+'/listing-matches/apply',{requestKey:request.current.key,rows});setDrafts({});setMessage('已處理人工選取列；未選列保持原樣。');await load(page);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>只處理人工選取列</Button></>}
 </Shell>;
}
export function SheetReferences({s,id}:{s:number;id:number}){const api=useImportApi(),[data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);return <div className="space-y-3"><p>Sheet 舊參考價不混入正式成交；原始公式只顯示，不執行。</p><Button className={action} variant="outline" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{setData(await api('/stores/'+s+'/catalog-products/'+id+'/sheet-references'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>讀取 Sheet 來源參考</Button>{error&&<p role="alert">{error}</p>}{data?.items.length===0&&<p>沒有已匯入來源。</p>}{data?.items.map((r:any,i:number)=><article key={i} className="space-y-2 border-t border-border pt-3"><p>{r.spreadsheetTitle} ／ {r.sheetTitle} · 第 {r.sourceRowNumber} 列 · {r.status}</p><details><summary className="min-h-11 py-2 underline">原始欄位與公式</summary><pre className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(r.rawValues,null,2)}</pre></details></article>)}</div>;}
export default function ProductDatabaseImport({mode='sheet'}:{mode?:'sheet'|'matches'}){return <StoreGate>{s=>mode==='matches'?<MatchesPage key={s} s={s}/>:<ImportPage key={s} s={s}/>}</StoreGate>;}
