import { useState,type ReactNode } from 'react';
import { Link,useLocation } from 'wouter';
import { catalogGet,catalogAliases,catalogAliasCreate,catalogAliasDelete,catalogCosts,catalogCostCreate,catalogCostVoid,catalogShopee,catalogShopeeCreate,catalogShopeeVoid,catalogRelationships,catalogRelationshipCreate,catalogRelationshipDelete,catalogAudit,catalogPatch,catalogCorrectBarcode,catalogClone,previewPricingV2,type PricingV2Preview } from '@workspace/api-client-react';
import { Button } from '@/components/ui/button';
import { Accordion,AccordionItem,AccordionTrigger,AccordionContent } from '@/components/ui/accordion';
import { Shell,StoreGate,Loading,Failure,Money,Status,panel,action,useCatalogQuery,useRefreshCatalog } from '@/components/product-database/shared';
import { ActionEditor,reasons,reasonErrors,adjustmentMode,modeOptions } from '@/components/product-database/ActionEditor';
import { catalogDateLabel,formatCatalogNumber,objectValue } from '@/lib/productDatabase';
import { CatalogListings } from '@/components/product-database/ListingSummary';
import {SheetReferences} from './ProductDatabaseImport';

const auditLabels:Record<string,string>={CATALOG_CREATED:'建立商品',CATALOG_UPDATED:'更新基本資料',CATALOG_ARCHIVED:'封存商品',BARCODE_CORRECTED:'更正條碼',CATALOG_CLONED:'複製為另一商品',COST_CREATED:'新增成本',COST_APPENDED:'追加成本',COST_VOIDED:'作廢成本',SHOPEE_RECORDED:'新增蝦皮參考',SHOPEE_VOIDED:'作廢蝦皮參考',ALIAS_CREATED:'新增別名',ALIAS_DELETED:'移除別名',RELATIONSHIP_CREATED:'新增關聯',RELATIONSHIP_DELETED:'移除關聯'};
function Section({id,title,children}:{id:string;title:string;children:ReactNode}){return <AccordionItem value={id} className={panel}><AccordionTrigger className="min-h-11 text-base focus-visible:ring-2 focus-visible:ring-ring">{title}</AccordionTrigger><AccordionContent className="space-y-4 motion-reduce:animate-none">{children}</AccordionContent></AccordionItem>;}
function Detail({s,id}:{s:number;id:number}){
 const api=useOrderApi(),[orderOpen,setOrderOpen]=useState(false);const sales=useCatalogQuery(s,['sales-reference',id],signal=>api(`/stores/${s}/catalog-products/${id}/sales-reference`,undefined,signal));
 const [,navigate]=useLocation(),refresh=useRefreshCatalog(s),[preview,setPreview]=useState<PricingV2Preview|null>(null);
 const p=useCatalogQuery(s,['product',id],signal=>catalogGet(s,id,{signal}));const aliases=useCatalogQuery(s,['aliases',id],signal=>catalogAliases(s,id,{signal}));const costs=useCatalogQuery(s,['costs',id],signal=>catalogCosts(s,id,{signal}));const shopee=useCatalogQuery(s,['shopee',id],signal=>catalogShopee(s,id,{signal}));const relationships=useCatalogQuery(s,['relationships',id],signal=>catalogRelationships(s,id,{signal}));const audit=useCatalogQuery(s,['audit',id],signal=>catalogAudit(s,id,{signal}));
 if(p.isError)return <Shell title="商品資料"><Failure error={p.error} retry={()=>void p.refetch()}/></Shell>;if(!p.data)return <Loading/>;const product=p.data.product;
 const historyState=(q:{isError:boolean;isPending:boolean;error:unknown;refetch:()=>unknown},empty:boolean)=>q.isError?<Failure error={q.error} retry={()=>void q.refetch()}/>:q.isPending?<Loading/>:empty?<p className="text-secondary-foreground">尚無紀錄。</p>:null;
 return <Shell title={product.name} actions={<><Button className={action} variant="outline" onClick={()=>setOrderOpen(true)}>加入訂單</Button><Button className={action} asChild><Link href={`/product-database/${id}/edit`}>編輯基本資料</Link></Button></>}><div className="mb-6 flex flex-wrap items-center gap-3"><Status status={product.status}/><p className="break-all text-secondary-foreground">{product.barcodeStatus==='NONE'?'無條碼':product.barcode}</p></div><Accordion type="multiple" defaultValue={['basic','cost']} className="space-y-4">
 <Section id="basic" title="基本資料"><dl className="space-y-2"><div>重量：{formatCatalogNumber(product.weightGrams,2)} g</div><div>原價：<Money value={product.currentCost?.originalPriceJpy}/></div><div>有效成本：<Money value={product.currentCost?.effectiveCostJpy}/></div><div>偏好路線：{product.preferredRouteLabel||'未指定'}</div><div className="break-words">內部備註：{product.internalNote||'未填寫'}</div></dl><p className="text-secondary-foreground">更新 {catalogDateLabel(product.updatedAt)}</p><div className="flex flex-wrap gap-2"><ActionEditor label={product.status==='ARCHIVED'?'還原商品':'封存商品'} fields={[]} description={product.status==='ARCHIVED'?'還原後可於正常商品中搜尋。':'封存後預設搜尋不顯示，所有歷史仍保留。'} submit={async()=>{await catalogPatch(s,id,{status:product.status==='ARCHIVED'?'NORMAL':'ARCHIVED'});await refresh();}}/><ActionEditor label={product.status==='DISCONTINUED'?'恢復正常':'設為店鋪停售'} fields={[]} description="停售仍可搜尋，不會修改既有上架或成交。" submit={async()=>{await catalogPatch(s,id,{status:product.status==='DISCONTINUED'?'NORMAL':'DISCONTINUED'});await refresh();}}/><ActionEditor label="更正條碼" description="修正這個商品的條碼，保留主檔與全部歷史；若是另一商品請使用換品複製。同碼衝突時請返回核對。" fields={[{key:'barcode',label:'正確條碼',initial:product.barcode,required:true},{key:'barcodeStatus',label:'條碼狀態',initial:product.barcodeStatus,options:[{value:'REAL',label:'有條碼'},{value:'NONE',label:'無條碼（0）'}]},...reasons]} validate={reasonErrors} submit={async v=>{await catalogCorrectBarcode(s,id,{barcode:v.barcodeStatus==='NONE'?'0':v.barcode,barcodeStatus:v.barcodeStatus==='NONE'?'NONE':'REAL',reasonCode:v.reasonCode,reasonText:v.reasonText||null});await refresh();}}/><ActionEditor label="換品複製" description="用不同的真實條碼建立獨立商品，原商品歷史保留；新商品從新的原價開始。" fields={[{key:'barcode',label:'新商品條碼',required:true},{key:'originalPriceJpy',label:'新商品原價 ¥',required:true,decimal:true},...reasons]} validate={reasonErrors} submit={async v=>{const result=await catalogClone(s,id,{barcode:v.barcode,barcodeStatus:'REAL',originalPriceJpy:v.originalPriceJpy,reasonCode:v.reasonCode,reasonText:v.reasonText||null});await refresh();navigate(`/product-database/${result.product.id}`);}}/></div><h3 className="font-semibold">歷史名稱與別名</h3>{historyState(aliases,!aliases.data?.items.length)}{aliases.data?.items.map(a=><div className="flex flex-wrap items-center justify-between gap-2" key={a.id}><p>{a.alias} · {a.source==='RENAMED'?'改名前名稱':'手動別名'}</p><ActionEditor label={`移除別名 ${a.alias}`} description="只移除此搜尋別名，稽核紀錄保留。" fields={[]} submit={async()=>{await catalogAliasDelete(s,id,a.id);await refresh();}}/></div>)}<ActionEditor label="新增別名" description="供日後使用不同名稱搜尋。" fields={[{key:'alias',label:'別名',required:true}]} submit={async v=>{await catalogAliasCreate(s,id,{alias:v.alias});await refresh();}}/></Section>
 <Section id="cost" title="成本歷史"><p className="text-secondary-foreground">成本只能追加或作廢，不覆寫舊成本，也不回算既有成交。</p><ActionEditor label="追加成本" description="請保留原價與有效成本的區別；一般原價使用 100%，倍率調整填小數。" fields={[{key:'originalPriceJpy',label:'日本原始售價 ¥',required:true,decimal:true},{key:'mode',label:'調整模式',initial:'NONE',options:modeOptions},{key:'adjustmentRate',label:'進貨倍率（倍率模式必填）',decimal:true},{key:'effectiveCostJpy',label:'人工有效成本 ¥（人工模式必填）',decimal:true},{key:'observedAt',label:'觀察日期',type:'date'},...reasons]} validate={v=>({...reasonErrors(v),...(v.mode==='RATE'&&!v.adjustmentRate?{adjustmentRate:'請填寫倍率'}:{}),...(v.mode==='MANUAL'&&!v.effectiveCostJpy?{effectiveCostJpy:'請填寫人工有效成本'}:{})})} submit={async v=>{await catalogCostCreate(s,id,{originalPriceJpy:v.originalPriceJpy,adjustmentMode:adjustmentMode(v.mode),...(v.mode==='RATE'?{adjustmentRate:v.adjustmentRate}:v.mode==='MANUAL'?{effectiveCostJpy:v.effectiveCostJpy}:{}),observedAt:v.observedAt||null,reasonCode:v.reasonCode,reasonText:v.reasonText||null});setPreview(null);await refresh();}}/>{historyState(costs,!costs.data?.items.length)}{costs.data?.items.map(c=><article key={c.id} className="space-y-2 border-t border-border pt-4"><h3 className="font-medium">{c.isCurrent?'● 目前成本':c.status==='VOIDED'?'已作廢':'歷史成本'}</h3><p className="flex flex-wrap gap-3">原價 <Money value={c.originalPriceJpy}/>；有效成本 <Money value={c.effectiveCostJpy}/></p><p className="text-secondary-foreground">{catalogDateLabel(c.observedAt)} · {c.adjustmentMode==='NONE'?'原價':c.adjustmentMode==='RATE'?`倍率 ${c.adjustmentRate}`:'人工成本'}</p>{c.status==='VOIDED'?<p className="break-words">作廢原因：{c.voidReasonText||c.voidReasonCode} · {catalogDateLabel(c.voidedAt)}</p>:<ActionEditor label={`作廢成本 #${c.id}`} description="作廢後回到最近仍有效的成本；全部作廢時變為待確認，不會復活已作廢項目。" fields={reasons} validate={reasonErrors} submit={async v=>{await catalogCostVoid(s,id,c.id,{reasonCode:v.reasonCode,reasonText:v.reasonText||null});setPreview(null);await refresh();}}/>}</article>)}</Section>
 <Section id="shopee" title="蝦皮參考"><ActionEditor label="新增蝦皮參考" description="只作價格參考，不當作正式成交統計。" fields={[{key:'priceTwd',label:'參考價 NT$',required:true,decimal:true},{key:'observedAt',label:'觀察日期',type:'date',required:true},{key:'sourceUrl',label:'來源網址'},...reasons]} validate={reasonErrors} submit={async v=>{await catalogShopeeCreate(s,id,{priceTwd:v.priceTwd,observedAt:v.observedAt,sourceUrl:v.sourceUrl||null,reasonCode:v.reasonCode,reasonText:v.reasonText||null});await refresh();}}/>{historyState(shopee,!shopee.data?.items.length)}{shopee.data?.items.map(r=><article key={r.id} className="space-y-2 border-t border-border pt-3"><p><Money value={r.priceTwd} currency="TWD"/> · {catalogDateLabel(r.observedAt)} · {r.status==='VOIDED'?'已作廢':'有效'}</p>{r.sourceUrl?<a href={r.sourceUrl} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center underline">查看來源</a>:null}{r.status==='ACTIVE'?<ActionEditor label={`作廢參考 #${r.id}`} description="保留價格與作廢紀錄。" fields={reasons} validate={reasonErrors} submit={async v=>{await catalogShopeeVoid(s,id,r.id,{reasonCode:v.reasonCode,reasonText:v.reasonText||null});await refresh();}}/>:null}</article>)}</Section>
 <Section id="listing" title="上架歷史"><CatalogListings s={s} catalogId={id}/></Section>
 <Section id="general" title="一般成交">{sales.isError?<Failure error={sales.error} retry={()=>void sales.refetch()}/>:<SalesSummary label="一般成交" sale={sales.data?.items[0]?.general}/>}<p>{sales.data?.currentReference.label}</p><p>以最近一般售價重算單位利潤 <Money currency="TWD" value={sales.data?.currentReference.generalUnitProfitTwd}/></p></Section>
 <Section id="vip" title="VIP 成交"><SalesSummary label="VIP 成交" sale={sales.data?.items[0]?.vip}/><p>以最近 VIP 售價重算單位利潤 <Money currency="TWD" value={sales.data?.currentReference.vipUnitProfitTwd}/></p></Section>
 <Section id="preview" title="目前重算"><p className="text-secondary-foreground">只供本次參考，不儲存售價。35% 目標參考不會自動填入一般售價。</p><ActionEditor label="試算本次利潤" description="使用目前有效成本；缺少成本或國際航運時仍顯示待確認。" fields={[{key:'generalPrice',label:'本次一般售價 NT$',required:true,decimal:true},{key:'exchangeRate',label:'本次進貨匯率',required:true,decimal:true},{key:'exempt',label:'本次路線運輸',initial:'no',options:[{value:'no',label:'未確認（保留待確認）'},{value:'yes',label:'明確免除路線運輸成本'}]}]} submit={async v=>{setPreview(await previewPricingV2(s,{originalPriceJpy:product.currentCost?.originalPriceJpy??null,effectiveCostJpy:product.currentCost?.effectiveCostJpy??null,weightGrams:product.weightGrams,...(product.defaultPricingTemplateId?{templateId:product.defaultPricingTemplateId}:{}),...(product.defaultDepartmentStoreFeeRate!==null?{departmentStoreFeeRate:product.defaultDepartmentStoreFeeRate}:{}),generalFinalPriceTwd:v.generalPrice,exchangeRate:v.exchangeRate,...(product.defaultShippingProfileId?{shippingProfileId:product.defaultShippingProfileId}:{}),isTransportCostExempt:v.exempt==='yes'}));}}/><p>目前淨利：<Money value={preview?.general.values.netProfitTwd} currency="TWD"/></p><p>35% 目標參考：<Money value={preview?.amounts.targetPriceTwd} currency="TWD"/></p>{preview?.status==='PENDING_CONFIRMATION'?<p role="status">尚有成本、售價或運費資料待確認，不能據此定價。</p>:null}</Section>
 <Section id="relationships" title="關聯與可能重複"><ActionEditor label="新增商品關聯" description="只標記關係，不合併商品或歷史。商品編號可從商品詳細頁網址取得。" fields={[{key:'target',label:'關聯商品編號',required:true},{key:'type',label:'關係',initial:'RELATED',options:[{value:'RELATED',label:'相關商品'},{value:'POSSIBLE_DUPLICATE',label:'可能重複'}]}]} submit={async v=>{await catalogRelationshipCreate(s,id,{targetCatalogProductId:Number(v.target),relationType:v.type==='POSSIBLE_DUPLICATE'?'POSSIBLE_DUPLICATE':'RELATED'});await refresh();}}/>{historyState(relationships,!relationships.data?.items.length)}{relationships.data?.items.map(r=>{const other=r.sourceCatalogProductId===id?r.targetCatalogProductId:r.sourceCatalogProductId;return <div key={r.id} className="flex flex-wrap items-center gap-2"><Link href={`/product-database/${other}`} className="inline-flex min-h-11 items-center underline">商品 #{other} · {r.relationType==='POSSIBLE_DUPLICATE'?'可能重複':'相關'}</Link><ActionEditor label={`移除關聯 #${r.id}`} description="不刪除任何商品。" fields={[]} submit={async()=>{await catalogRelationshipDelete(s,id,r.id);await refresh();}}/></div>;})}</Section>
 <Section id="sheet" title="Sheet 來源"><SheetReferences s={s} id={id}/></Section>
 <Section id="audit" title="修改紀錄"><p className="text-secondary-foreground">最新紀錄在前</p>{historyState(audit,!audit.data?.items.length)}{audit.data?.items.slice().reverse().map(event=>{const reason=objectValue(event.details.reason);return <article key={event.id} className="border-t border-border py-3"><h3>{auditLabels[event.action]??'商品資料變更'}</h3><p className="break-all text-sm text-secondary-foreground">{catalogDateLabel(event.createdAt)} · {event.actor}</p>{typeof reason?.text==='string'?<p>{reason.text}</p>:null}</article>;})}</Section>
 </Accordion><CreateOrderDialog storeId={s} open={orderOpen} initialCatalog={product} onClose={()=>setOrderOpen(false)}/></Shell>;
}
export default function ProductDatabaseDetail({productId}:{productId:number}){if(!Number.isSafeInteger(productId)||productId<1)return <Shell title="商品不存在"><p>網址中的商品編號無效。</p></Shell>;return <StoreGate>{s=><Detail key={productId} s={s} id={productId}/>}</StoreGate>;}
import {CreateOrderDialog} from "./CreateOrderDialog";
import {useOrderApi} from "@/components/product-database/OrderItemsEditor";
import {SalesSummary} from "@/components/product-database/SalesSummary";
