import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { action, control, Field, ErrorSummary } from './shared';
import { catalogError, decimalInput } from '@/lib/productDatabase';

export type EditorField={key:string;label:string;initial?:string;required?:boolean;decimal?:boolean;type?:string;options?:{value:string;label:string}[]};
export function ActionEditor({label,title,description,fields,submit,validate}:{label:string;title?:string;description:string;fields:EditorField[];submit:(values:Record<string,string>)=>Promise<unknown>;validate?:(values:Record<string,string>)=>Record<string,string|undefined>}){
 const [open,setOpen]=useState(false),[values,setValues]=useState<Record<string,string>>({}),[errors,setErrors]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[pending,setPending]=useState(false),[notice,setNotice]=useState('');
 const trigger=useRef<HTMLButtonElement>(null),focusScope=useRef<HTMLElement|null>(null);
 const prefix=label.replace(/\s/g,'');
 async function save(){const invalid:Record<string,string>={};for(const f of fields){if(f.required&&!values[f.key]?.trim())invalid[f.key]=`請填寫${f.label}`;else if(f.decimal&&values[f.key]&&!decimalInput(values[f.key]))invalid[f.key]=`${f.label}須為非負十進位數`;}for(const [key,value] of Object.entries(validate?.(values)??{}))if(value)invalid[key]=value;setErrors(Object.fromEntries(Object.entries(invalid).map(([key,v])=>[`${prefix}-${key}`,v])));setMessage('');if(Object.keys(invalid).length)return;setPending(true);try{await submit(values);setOpen(false);setNotice('已儲存');}catch(e){setMessage(catalogError(e));}finally{setPending(false);}}
 return <><Button ref={trigger} variant="outline" className={action} onClick={()=>{focusScope.current=trigger.current?.closest<HTMLElement>('[role="dialog"],section,main')??null;setValues(Object.fromEntries(fields.map(f=>[f.key,f.initial??''])));setErrors({});setMessage('');setNotice('');setOpen(true);}}>{label}</Button><span className="sr-only" role="status">{notice}</span><Dialog open={open} onOpenChange={v=>{if(!pending)setOpen(v);}}><DialogContent onCloseAutoFocus={e=>{const target=trigger.current?.isConnected?trigger.current:focusScope.current?.isConnected?focusScope.current.querySelector<HTMLElement>('button:not([disabled]),a[href]'):null;if(target){e.preventDefault();target.focus();}}} className="max-h-[85dvh] overflow-y-auto [&>button]:min-h-11 [&>button]:min-w-11"><DialogTitle>{title??label}</DialogTitle><DialogDescription>{description}</DialogDescription><form className="space-y-4" onSubmit={e=>{e.preventDefault();void save();}} noValidate><ErrorSummary errors={errors} message={message}/>{fields.map(f=>f.options?<div className="space-y-2" key={f.key}><label htmlFor={`${prefix}-${f.key}`}>{f.label}</label><select id={`${prefix}-${f.key}`} className={control} aria-invalid={!!errors[`${prefix}-${f.key}`]} aria-describedby={errors[`${prefix}-${f.key}`]?`${prefix}-${f.key}-error`:undefined} value={values[f.key]??''} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}>{f.options.map(o=><option value={o.value} key={o.value}>{o.label}</option>)}</select>{errors[`${prefix}-${f.key}`]?<p id={`${prefix}-${f.key}-error`} className="text-sm text-destructive">{errors[`${prefix}-${f.key}`]}</p>:null}</div>:<Field id={`${prefix}-${f.key}`} key={f.key} label={f.label} value={values[f.key]??''} onChange={v=>setValues(old=>({...old,[f.key]:v}))} error={errors[`${prefix}-${f.key}`]} type={f.type} inputMode={f.decimal?'decimal':undefined}/>)}<div className="flex flex-wrap gap-2"><Button className={action} type="submit" disabled={pending}>{pending?'儲存中…':'確認儲存'}</Button><Button className={action} type="button" variant="outline" disabled={pending} onClick={()=>setOpen(false)}>取消</Button></div></form></DialogContent></Dialog></>;
}
export const reasons:EditorField[]=[{key:'reasonCode',label:'原因',initial:'UPDATED',options:[{value:'UPDATED',label:'資料更新'},{value:'ERROR',label:'輸入錯誤'},{value:'OTHER',label:'其他'}]},{key:'reasonText',label:'原因說明（其他必填）'}];
export const reasonErrors=(v:Record<string,string>):Record<string,string>=>v.reasonCode==='OTHER'&&!v.reasonText.trim()?{reasonText:'選擇其他原因時，請填寫說明'}:{};
export const adjustmentMode=(value:string):'NONE'|'RATE'|'MANUAL'=>value==='RATE'?'RATE':value==='MANUAL'?'MANUAL':'NONE';
export const modeOptions=[{value:'NONE',label:'原價（100%）'},{value:'RATE',label:'倍率調整'},{value:'MANUAL',label:'人工有效成本'}];
