import { useState } from 'react';
import { catalogSettingsGet,catalogInitialize,catalogSettingsPatch,catalogTemplateCreate,catalogTemplatePatch,catalogTemplateDelete,catalogShippingCreate,catalogShippingPatch,catalogShippingDelete } from '@workspace/api-client-react';
import { Button } from '@/components/ui/button';
import { Loading,Failure,Money,action,useCatalogQuery,useRefreshCatalog } from './shared';
import { ActionEditor,adjustmentMode,modeOptions,type EditorField } from './ActionEditor';
import { catalogError } from '@/lib/productDatabase';

export function CatalogSettingsPanel({s}:{s:number}){
 const query=useCatalogQuery(s,['settings'],signal=>catalogSettingsGet(s,{signal})),refresh=useRefreshCatalog(s);const [pending,setPending]=useState(false),[error,setError]=useState('');
 if(query.isError)return <Failure error={query.error} retry={()=>void query.refetch()}/>;if(!query.data)return <Loading/>;const data=query.data;
 const shippingOptions=[{value:'',label:'未指定'},...data.shippingProfiles.filter(p=>p.isActive).map(p=>({value:String(p.id),label:p.name}))];
 const templateFields=(initial?:typeof data.templates[number]):EditorField[]=>[{key:'name',label:'範本名稱',required:true,initial:initial?.name},{key:'mode',label:'成本模式',initial:initial?.costAdjustmentMode??'NONE',options:modeOptions},{key:'rate',label:'進貨倍率',decimal:true,required:true,initial:initial?.costAdjustmentRate??'1'},{key:'fee',label:'百貨手續費率',decimal:true,required:true,initial:initial?.departmentStoreFeeRate??'0'},{key:'shipping',label:'預設國際航運',initial:initial?.defaultShippingProfileId?String(initial.defaultShippingProfileId):'',options:shippingOptions}];
 const shipFields=(initial?:typeof data.shippingProfiles[number]):EditorField[]=>[{key:'name',label:'航運名稱',required:true,initial:initial?.name},...(!initial?[{key:'code',label:'航運代碼',required:true}]:[]),{key:'rate',label:'運費 NT$',required:true,decimal:true,initial:initial?.rateTwd},{key:'basis',label:'基準重量 g',required:true,decimal:true,initial:initial?.basisWeightGrams}];
 return <div className="space-y-6"><section className="space-y-3"><h3 className="font-semibold">系統預設草稿</h3><p className="text-sm text-secondary-foreground">一般／連線：原價 100%；香水：91.5%、百貨費 1.55%。一般空運 NT$ 220／1000 g；虎航 NT$ 1,050／20000 g。目標毛利 35% 只供參考。</p><Button className={action} variant="outline" disabled={pending} onClick={async()=>{setPending(true);setError('');try{await catalogInitialize(s,{});await refresh();}catch(e){setError(catalogError(e));}finally{setPending(false);}}}>{pending?'建立中…':'明確建立系統預設'}</Button><p className="text-sm text-secondary-foreground">重複操作不覆蓋已修改設定。建立前不會儲存任何草稿。</p>{error?<p role="alert">{error}</p>:null}</section>
 <section className="space-y-3"><h3 className="font-semibold">計價參數</h3><p className="text-sm text-secondary-foreground">設定版本 {data.settings.settingsVersion}</p><ActionEditor label="編輯計價參數" description="只影響後續重算，不改既有成交與快照。倍率使用小數，例如 35% 填 0.35。" fields={([{key:'targetMarginRate',label:'目標毛利率'},{key:'lossProtectionTwd',label:'損耗保護 NT$'},{key:'purchasePaymentFeeRate',label:'進貨付款費率'},{key:'routePaymentFeeRate',label:'路線付款費率'},{key:'profitLossMaxTwd',label:'虧損警示門檻 NT$'},{key:'profitLowMaxTwd',label:'低利潤門檻 NT$'},{key:'profitMediumMaxTwd',label:'中利潤門檻 NT$'}] as const).map(f=>({...f,initial:data.settings[f.key],required:true}))} submit={async v=>{await catalogSettingsPatch(s,{targetMarginRate:v.targetMarginRate,lossProtectionTwd:v.lossProtectionTwd,purchasePaymentFeeRate:v.purchasePaymentFeeRate,routePaymentFeeRate:v.routePaymentFeeRate,profitLossMaxTwd:v.profitLossMaxTwd,profitLowMaxTwd:v.profitLowMaxTwd,profitMediumMaxTwd:v.profitMediumMaxTwd});await refresh();}}/></section>
 <section className="space-y-3"><h3 className="font-semibold">成交過期提醒</h3><p>目前 {data.settings.staleSaleDays} 天；沒有可靠成交日期時顯示未知。</p><ActionEditor label="設定成交過期天數" description="只變更提醒，不改歷史成本。" fields={[{key:'days',label:'成交過期天數',initial:String(data.settings.staleSaleDays),required:true}]} validate={v=>/^[1-9]\d*$/.test(v.days)&&Number(v.days)<=2147483647?{}:{days:'請填寫 1～2147483647 的正整數'}} submit={async v=>{await catalogSettingsPatch(s,{staleSaleDays:Number(v.days)});await refresh();}}/></section>
 <section className="space-y-3"><h3 className="font-semibold">計價範本</h3>{!data.templates.length?<p className="text-secondary-foreground">尚未建立，請先明確建立系統預設。</p>:null}{data.templates.map(t=><div key={t.id} className="space-y-2 border-t border-border pt-3"><p>{t.name} · {t.isActive?'啟用':'停用'} · 倍率 {t.costAdjustmentRate}</p><div className="flex flex-wrap gap-2"><ActionEditor label={`編輯${t.name}`} fields={templateFields(t)} description="既有成本不會回算。" submit={async v=>{await catalogTemplatePatch(s,t.id,{name:v.name,costAdjustmentMode:adjustmentMode(v.mode),costAdjustmentRate:v.rate,departmentStoreFeeRate:v.fee,defaultShippingProfileId:v.shipping?Number(v.shipping):null});await refresh();}}/><ActionEditor label={`${t.isActive?'停用':'啟用'}${t.name}`} fields={[]} description="停用後不能套用於新的商品，原引用保留。" submit={async()=>{await catalogTemplatePatch(s,t.id,{isActive:!t.isActive});await refresh();}}/><ActionEditor label={`刪除${t.name}`} fields={[]} description="已使用的範本不能刪除，請改用停用。" submit={async()=>{await catalogTemplateDelete(s,t.id);await refresh();}}/></div></div>)}<ActionEditor label="新增自訂範本" fields={templateFields()} description="新增可重用的成本設定，不會變更商品歷史。" submit={async v=>{await catalogTemplateCreate(s,{code:'CUSTOM',name:v.name,costAdjustmentMode:adjustmentMode(v.mode),costAdjustmentRate:v.rate,departmentStoreFeeRate:v.fee,defaultShippingProfileId:v.shipping?Number(v.shipping):null});await refresh();}}/></section>
 <section className="space-y-3"><h3 className="font-semibold">國際航運</h3>{data.shippingProfiles.map(p=><div key={p.id} className="space-y-2 border-t border-border pt-3"><p>{p.name} · <Money value={p.rateTwd} currency="TWD"/>／{p.basisWeightGrams} g · {p.isActive?'啟用':'停用'}</p><div className="flex flex-wrap gap-2"><ActionEditor label={`編輯${p.name}`} fields={shipFields(p)} description="國際航運與台灣寄件費分開計算。" submit={async v=>{await catalogShippingPatch(s,p.id,{name:v.name,rateTwd:v.rate,basisWeightGrams:v.basis});await refresh();}}/><ActionEditor label={`${p.isActive?'停用':'啟用'}${p.name}`} fields={[]} description="只影響後續選用。" submit={async()=>{await catalogShippingPatch(s,p.id,{isActive:!p.isActive});await refresh();}}/><ActionEditor label={`刪除${p.name}`} fields={[]} description="已被引用的設定無法刪除。" submit={async()=>{await catalogShippingDelete(s,p.id);await refresh();}}/></div></div>)}<ActionEditor label="新增國際航運" fields={shipFields()} description="填寫以台幣計價的費用及其基準重量。" submit={async v=>{await catalogShippingCreate(s,{name:v.name,code:v.code,rateTwd:v.rate,basisWeightGrams:v.basis});await refresh();}}/></section></div>;
}
