// Phase 1 foundation. SQL 0041 additionally installs immutable triggers and
// tenant guards for the two legacy optional catalog hints; use SQL to migrate.
import { pgTable, serial, integer, text, numeric, boolean, timestamp, date, jsonb, check, unique, uniqueIndex, index, foreignKey } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { storesTable } from "./stores.ts";
import { productsTable } from "./products.ts";
import { catalogProductsTable, productCostRecordsTable } from "./catalogProducts.ts";

export const listingPricingSnapshotsTable = pgTable("listing_pricing_snapshots", {
  id: serial("id").primaryKey(),
  storeId: integer("store_id").notNull(),
  productId: integer("product_id").notNull(),
  catalogProductId: integer("catalog_product_id"),
  sourceCostRecordId: integer("source_cost_record_id"),
  listingBarcode: text("listing_barcode"),
  pricingContext: jsonb("pricing_context"),
  createdBy: text("created_by"),
  originalPriceJpy: numeric("original_price_jpy", { precision: 30, scale: 12 }),
  effectiveCostJpy: numeric("effective_cost_jpy", { precision: 30, scale: 12 }),
  exchangeRate: numeric("exchange_rate", { precision: 30, scale: 12 }),
  routeCostTwd: numeric("route_cost_twd", { precision: 30, scale: 12 }),
  lossProtectionTwd: numeric("loss_protection_twd", { precision: 30, scale: 12 }),
  protectedRouteCostTwd: numeric("protected_route_cost_twd", { precision: 30, scale: 12 }),
  internationalShippingTwd: numeric("international_shipping_twd", { precision: 30, scale: 12 }),
  purchasePaymentFeeRate: numeric("purchase_payment_fee_rate", { precision: 30, scale: 12 }),
  purchasePaymentFeeTwd: numeric("purchase_payment_fee_twd", { precision: 30, scale: 12 }),
  routePaymentFeeRate: numeric("route_payment_fee_rate", { precision: 30, scale: 12 }),
  departmentStoreFeeRate: numeric("department_store_fee_rate", { precision: 30, scale: 12 }),
  departmentStoreFeeTwd: numeric("department_store_fee_twd", { precision: 30, scale: 12 }),
  originalPriceTwd: numeric("original_price_twd", { precision: 30, scale: 12 }),
  effectiveProductCostTwd: numeric("effective_product_cost_twd", { precision: 30, scale: 12 }),
  totalCostTwd: numeric("total_cost_twd", { precision: 30, scale: 12 }),
  targetPriceTwd: numeric("target_price_twd", { precision: 30, scale: 12 }),
  weightGrams: numeric("weight_grams", { precision: 12, scale: 2 }),
  tripRouteId: integer("trip_route_id"),
  internationalShippingProfileSnapshot: jsonb("international_shipping_profile_snapshot"),
  generalFinalPriceTwd: numeric("general_final_price_twd", { precision: 10, scale: 2 }),
  vipFinalPriceTwd: numeric("vip_final_price_twd", { precision: 10, scale: 2 }),
  generalNetProfitTwd: numeric("general_net_profit_twd", { precision: 30, scale: 12 }),
  generalProfitRate: numeric("general_profit_rate", { precision: 30, scale: 12 }),
  generalContributionProfitTwd: numeric("general_contribution_profit_twd", { precision: 30, scale: 12 }),
  generalContributionProfitRate: numeric("general_contribution_profit_rate", { precision: 30, scale: 12 }),
  generalPerceivedDifferenceTwd: numeric("general_perceived_difference_twd", { precision: 30, scale: 12 }),
  vipNetProfitTwd: numeric("vip_net_profit_twd", { precision: 30, scale: 12 }),
  vipProfitRate: numeric("vip_profit_rate", { precision: 30, scale: 12 }),
  vipContributionProfitTwd: numeric("vip_contribution_profit_twd", { precision: 30, scale: 12 }),
  vipContributionProfitRate: numeric("vip_contribution_profit_rate", { precision: 30, scale: 12 }),
  vipPerceivedDifferenceTwd: numeric("vip_perceived_difference_twd", { precision: 30, scale: 12 }),
  generalProfitLevel: text("general_profit_level"),
  vipProfitLevel: text("vip_profit_level"),
  formulaVersion: text("formula_version").notNull(),
  settingsVersion: text("settings_version").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql.raw("now()")),
}, (t) => [
  unique("listing_pricing_snapshots_store_id_key").on(t.storeId, t.id),
  foreignKey({ name: "listing_source_cost_fk", columns: [t.storeId, t.sourceCostRecordId], foreignColumns: [productCostRecordsTable.storeId, productCostRecordsTable.id] }).onDelete("restrict"),
  unique("listing_pricing_snapshots_product_id_key").on(t.storeId, t.productId, t.id),
  foreignKey({ name: "listing_pricing_snapshots_store_fk", columns: [t.storeId], foreignColumns: [storesTable.id] }).onDelete("restrict"),
  foreignKey({ name: "listing_pricing_snapshots_product_fk", columns: [t.storeId, t.productId], foreignColumns: [productsTable.storeId, productsTable.id] }).onDelete("restrict"),
  foreignKey({ name: "listing_pricing_snapshots_catalog_fk", columns: [t.storeId, t.catalogProductId], foreignColumns: [catalogProductsTable.storeId, catalogProductsTable.id] }).onDelete("restrict"),
  check("listing_pricing_snapshots_original_price_jpy_valid", sql.raw("original_price_jpy <> 'NaN'::numeric AND original_price_jpy >= 0")),
  check("listing_pricing_snapshots_effective_cost_jpy_valid", sql.raw("effective_cost_jpy <> 'NaN'::numeric AND effective_cost_jpy >= 0")),
  check("listing_pricing_snapshots_exchange_rate_valid", sql.raw("exchange_rate <> 'NaN'::numeric AND exchange_rate >= 0")),
  check("listing_pricing_snapshots_route_cost_twd_valid", sql.raw("route_cost_twd <> 'NaN'::numeric AND route_cost_twd >= 0")),
  check("listing_pricing_snapshots_loss_protection_twd_valid", sql.raw("loss_protection_twd <> 'NaN'::numeric AND loss_protection_twd >= 0")),
  check("listing_pricing_snapshots_protected_route_cost_twd_valid", sql.raw("protected_route_cost_twd <> 'NaN'::numeric AND protected_route_cost_twd >= 0")),
  check("listing_pricing_snapshots_international_shipping_twd_valid", sql.raw("international_shipping_twd <> 'NaN'::numeric AND international_shipping_twd >= 0")),
  check("listing_pricing_snapshots_purchase_payment_fee_rate_valid", sql.raw("purchase_payment_fee_rate <> 'NaN'::numeric AND purchase_payment_fee_rate >= 0")),
  check("listing_pricing_snapshots_purchase_payment_fee_twd_valid", sql.raw("purchase_payment_fee_twd <> 'NaN'::numeric AND purchase_payment_fee_twd >= 0")),
  check("listing_pricing_snapshots_route_payment_fee_rate_valid", sql.raw("route_payment_fee_rate <> 'NaN'::numeric AND route_payment_fee_rate >= 0")),
  check("listing_pricing_snapshots_department_store_fee_rate_valid", sql.raw("department_store_fee_rate <> 'NaN'::numeric AND department_store_fee_rate >= 0")),
  check("listing_pricing_snapshots_department_store_fee_twd_valid", sql.raw("department_store_fee_twd <> 'NaN'::numeric AND department_store_fee_twd >= 0")),
  check("listing_pricing_snapshots_original_price_twd_valid", sql.raw("original_price_twd <> 'NaN'::numeric AND original_price_twd >= 0")),
  check("listing_pricing_snapshots_effective_product_cost_twd_valid", sql.raw("effective_product_cost_twd <> 'NaN'::numeric AND effective_product_cost_twd >= 0")),
  check("listing_pricing_snapshots_total_cost_twd_valid", sql.raw("total_cost_twd <> 'NaN'::numeric AND total_cost_twd >= 0")),
  check("listing_pricing_snapshots_target_price_twd_valid", sql.raw("target_price_twd <> 'NaN'::numeric AND target_price_twd >= 0")),
  check("listing_pricing_snapshots_weight_grams_valid", sql.raw("weight_grams <> 'NaN'::numeric AND weight_grams >= 0")),
  check("listing_pricing_snapshots_general_final_price_twd_valid", sql.raw("general_final_price_twd <> 'NaN'::numeric AND general_final_price_twd >= 0")),
  check("listing_pricing_snapshots_vip_final_price_twd_valid", sql.raw("vip_final_price_twd <> 'NaN'::numeric AND vip_final_price_twd >= 0")),
  check("listing_pricing_snapshots_general_net_profit_twd_valid", sql.raw("general_net_profit_twd <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_general_profit_rate_valid", sql.raw("general_profit_rate <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_general_contribution_profit_twd_valid", sql.raw("general_contribution_profit_twd <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_general_contribution_profit__1", sql.raw("general_contribution_profit_rate <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_general_perceived_difference_2", sql.raw("general_perceived_difference_twd <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_vip_net_profit_twd_valid", sql.raw("vip_net_profit_twd <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_vip_profit_rate_valid", sql.raw("vip_profit_rate <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_vip_contribution_profit_twd_valid", sql.raw("vip_contribution_profit_twd <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_vip_contribution_profit_rate_valid", sql.raw("vip_contribution_profit_rate <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_vip_perceived_difference_twd_valid", sql.raw("vip_perceived_difference_twd <> 'NaN'::numeric")),
  check("listing_pricing_snapshots_exchange_positive", sql.raw("exchange_rate > 0")),
  check("listing_pricing_snapshots_general_profit_level_valid", sql.raw("general_profit_level IN ('LOSS','LOW','MEDIUM','HIGH')")),
  check("listing_pricing_snapshots_vip_profit_level_valid", sql.raw("vip_profit_level IN ('LOSS','LOW','MEDIUM','HIGH')")),
]);

export const listingCurrentPricingSnapshotsTable = pgTable("listing_current_pricing_snapshots", {
  id: serial("id").primaryKey(),
  storeId: integer("store_id").notNull(),
  productId: integer("product_id").notNull(),
  snapshotId: integer("snapshot_id").notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().default(sql.raw("now()")),
}, (t) => [
  unique("listing_current_pricing_snapshots_store_id_key").on(t.storeId, t.id),
  unique("listing_current_pricing_snapshots_listing_key").on(t.storeId, t.productId),
  foreignKey({ name: "listing_current_pricing_snapshots_store_fk", columns: [t.storeId], foreignColumns: [storesTable.id] }).onDelete("restrict"),
  foreignKey({ name: "listing_current_pricing_snapshots_product_fk", columns: [t.storeId, t.productId], foreignColumns: [productsTable.storeId, productsTable.id] }).onDelete("restrict"),
  foreignKey({ name: "listing_current_pricing_snapshots_snapshot_fk", columns: [t.storeId, t.productId, t.snapshotId], foreignColumns: [listingPricingSnapshotsTable.storeId, listingPricingSnapshotsTable.productId, listingPricingSnapshotsTable.id] }).onDelete("restrict"),
]);
