// Phase 1 foundation. SQL 0041 additionally installs immutable triggers and
// tenant guards for the two legacy optional catalog hints; use SQL to migrate.
import { pgTable, serial, integer, text, numeric, boolean, timestamp, date, jsonb, check, unique, uniqueIndex, index, foreignKey } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { storesTable } from "./stores.ts";
import { ordersTable } from "./orders.ts";
import { catalogProductsTable } from "./catalogProducts.ts";
import { productsTable } from "./products.ts";

export const orderItemsTable = pgTable("order_items", {
  id: serial("id").primaryKey(),
  storeId: integer("store_id").notNull(),
  orderId: integer("order_id").notNull(),
  catalogProductId: integer("catalog_product_id"),
  listingProductId: integer("listing_product_id"),
  productNameSnapshot: text("product_name_snapshot").notNull(),
  barcodeSnapshot: text("barcode_snapshot"),
  quantity: integer("quantity").notNull(),
  unitPriceTwd: numeric("unit_price_twd", { precision: 10, scale: 2 }).notNull(),
  subtotalTwd: numeric("subtotal_twd", { precision: 30, scale: 12 }).notNull(),
  originalPriceJpySnapshot: numeric("original_price_jpy_snapshot", { precision: 30, scale: 12 }),
  effectiveCostJpySnapshot: numeric("effective_cost_jpy_snapshot", { precision: 30, scale: 12 }),
  exchangeRateSnapshot: numeric("exchange_rate_snapshot", { precision: 30, scale: 12 }),
  routeCostTwdSnapshot: numeric("route_cost_twd_snapshot", { precision: 30, scale: 12 }),
  lossProtectionTwdSnapshot: numeric("loss_protection_twd_snapshot", { precision: 30, scale: 12 }),
  protectedRouteCostTwdSnapshot: numeric("protected_route_cost_twd_snapshot", { precision: 30, scale: 12 }),
  internationalShippingTwdSnapshot: numeric("international_shipping_twd_snapshot", { precision: 30, scale: 12 }),
  purchasePaymentFeeRateSnapshot: numeric("purchase_payment_fee_rate_snapshot", { precision: 30, scale: 12 }),
  purchasePaymentFeeTwdSnapshot: numeric("purchase_payment_fee_twd_snapshot", { precision: 30, scale: 12 }),
  routePaymentFeeRateSnapshot: numeric("route_payment_fee_rate_snapshot", { precision: 30, scale: 12 }),
  departmentStoreFeeRateSnapshot: numeric("department_store_fee_rate_snapshot", { precision: 30, scale: 12 }),
  departmentStoreFeeTwdSnapshot: numeric("department_store_fee_twd_snapshot", { precision: 30, scale: 12 }),
  totalCostTwdSnapshot: numeric("total_cost_twd_snapshot", { precision: 30, scale: 12 }),
  weightGramsSnapshot: numeric("weight_grams_snapshot", { precision: 12, scale: 2 }),
  tripRouteIdSnapshot: integer("trip_route_id_snapshot"),
  internationalShippingProfileSnapshot: jsonb("international_shipping_profile_snapshot"),
  unitProfitTwdSnapshot: numeric("unit_profit_twd_snapshot", { precision: 30, scale: 12 }),
  profitRateSnapshot: numeric("profit_rate_snapshot", { precision: 30, scale: 12 }),
  contributionProfitTwdSnapshot: numeric("contribution_profit_twd_snapshot", { precision: 30, scale: 12 }),
  contributionProfitRateSnapshot: numeric("contribution_profit_rate_snapshot", { precision: 30, scale: 12 }),
  perceivedDifferenceTwdSnapshot: numeric("perceived_difference_twd_snapshot", { precision: 30, scale: 12 }),
  profitLevelSnapshot: text("profit_level_snapshot"),
  profitSnapshotStatus: text("profit_snapshot_status").notNull().default(sql.raw("'PENDING'")),
  customerTierSnapshot: text("customer_tier_snapshot").notNull().default(sql.raw("'UNKNOWN'")),
  priceSourceSnapshot: text("price_source_snapshot").notNull().default(sql.raw("'UNKNOWN'")),
  formulaVersion: text("formula_version"),
  settingsVersion: text("settings_version"),
  specValues: jsonb("spec_values").$type<Record<string, string>>().notNull().default({}),
  captureContext: jsonb("capture_context").$type<Record<string, unknown>>(),
  capturedAt: timestamp("captured_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql.raw("now()")),
}, (t) => [
  unique("order_items_store_id_key").on(t.storeId, t.id),
  foreignKey({ name: "order_items_store_fk", columns: [t.storeId], foreignColumns: [storesTable.id] }).onDelete("restrict"),
  foreignKey({ name: "order_items_order_fk", columns: [t.storeId, t.orderId], foreignColumns: [ordersTable.storeId, ordersTable.id] }).onDelete("restrict"),
  foreignKey({ name: "order_items_catalog_fk", columns: [t.storeId, t.catalogProductId], foreignColumns: [catalogProductsTable.storeId, catalogProductsTable.id] }).onDelete("restrict"),
  foreignKey({ name: "order_items_listing_fk", columns: [t.storeId, t.listingProductId], foreignColumns: [productsTable.storeId, productsTable.id] }).onDelete("restrict"),
  check("order_items_original_price_jpy_snapshot_valid", sql.raw("original_price_jpy_snapshot <> 'NaN'::numeric AND original_price_jpy_snapshot >= 0")),
  check("order_items_effective_cost_jpy_snapshot_valid", sql.raw("effective_cost_jpy_snapshot <> 'NaN'::numeric AND effective_cost_jpy_snapshot >= 0")),
  check("order_items_exchange_rate_snapshot_valid", sql.raw("exchange_rate_snapshot <> 'NaN'::numeric AND exchange_rate_snapshot >= 0")),
  check("order_items_route_cost_twd_snapshot_valid", sql.raw("route_cost_twd_snapshot <> 'NaN'::numeric AND route_cost_twd_snapshot >= 0")),
  check("order_items_loss_protection_twd_snapshot_valid", sql.raw("loss_protection_twd_snapshot <> 'NaN'::numeric AND loss_protection_twd_snapshot >= 0")),
  check("order_items_protected_route_cost_twd_snapshot_valid", sql.raw("protected_route_cost_twd_snapshot <> 'NaN'::numeric AND protected_route_cost_twd_snapshot >= 0")),
  check("order_items_international_shipping_twd_snapshot_valid", sql.raw("international_shipping_twd_snapshot <> 'NaN'::numeric AND international_shipping_twd_snapshot >= 0")),
  check("order_items_purchase_payment_fee_rate_snapshot_valid", sql.raw("purchase_payment_fee_rate_snapshot <> 'NaN'::numeric AND purchase_payment_fee_rate_snapshot >= 0")),
  check("order_items_purchase_payment_fee_twd_snapshot_valid", sql.raw("purchase_payment_fee_twd_snapshot <> 'NaN'::numeric AND purchase_payment_fee_twd_snapshot >= 0")),
  check("order_items_route_payment_fee_rate_snapshot_valid", sql.raw("route_payment_fee_rate_snapshot <> 'NaN'::numeric AND route_payment_fee_rate_snapshot >= 0")),
  check("order_items_department_store_fee_rate_snapshot_valid", sql.raw("department_store_fee_rate_snapshot <> 'NaN'::numeric AND department_store_fee_rate_snapshot >= 0")),
  check("order_items_department_store_fee_twd_snapshot_valid", sql.raw("department_store_fee_twd_snapshot <> 'NaN'::numeric AND department_store_fee_twd_snapshot >= 0")),
  check("order_items_total_cost_twd_snapshot_valid", sql.raw("total_cost_twd_snapshot <> 'NaN'::numeric AND total_cost_twd_snapshot >= 0")),
  check("order_items_unit_price_twd_valid", sql.raw("unit_price_twd <> 'NaN'::numeric AND unit_price_twd >= 0")),
  check("order_items_subtotal_twd_valid", sql.raw("subtotal_twd <> 'NaN'::numeric AND subtotal_twd >= 0")),
  check("order_items_weight_grams_snapshot_valid", sql.raw("weight_grams_snapshot <> 'NaN'::numeric AND weight_grams_snapshot >= 0")),
  check("order_items_unit_profit_twd_snapshot_valid", sql.raw("unit_profit_twd_snapshot <> 'NaN'::numeric")),
  check("order_items_profit_rate_snapshot_valid", sql.raw("profit_rate_snapshot <> 'NaN'::numeric")),
  check("order_items_contribution_profit_twd_snapshot_valid", sql.raw("contribution_profit_twd_snapshot <> 'NaN'::numeric")),
  check("order_items_contribution_profit_rate_snapshot_valid", sql.raw("contribution_profit_rate_snapshot <> 'NaN'::numeric")),
  check("order_items_perceived_difference_twd_snapshot_valid", sql.raw("perceived_difference_twd_snapshot <> 'NaN'::numeric")),
  check("order_items_quantity_positive", sql.raw("quantity > 0")),
  check("order_items_subtotal_exact", sql.raw("subtotal_twd = unit_price_twd * quantity")),
  check("order_items_exchange_positive", sql.raw("exchange_rate_snapshot > 0")),
  check("order_items_profit_snapshot_status_valid", sql.raw("profit_snapshot_status IN ('PENDING','CAPTURED','EXEMPT')")),
  check("order_items_customer_tier_snapshot_valid", sql.raw("customer_tier_snapshot IN ('general','vip','wholesale','partner','UNKNOWN')")),
  check("order_items_price_source_snapshot_valid", sql.raw("price_source_snapshot IN ('general','tier','UNKNOWN')")),
  check("order_items_profit_level_snapshot_valid", sql.raw("profit_level_snapshot IN ('LOSS','LOW','MEDIUM','HIGH')")),
]);

export const orderCompletionEventsTable = pgTable("order_completion_events", {
  id: serial("id").primaryKey(),
  storeId: integer("store_id").notNull(),
  orderId: integer("order_id").notNull(),
  eventKey: text("event_key").notNull(),
  fromStatus: text("from_status").notNull(),
  toStatus: text("to_status").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  source: text("source").notNull(),
  actorId: text("actor_id"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().default(sql.raw("now()")),
}, (t) => [
  unique("order_completion_events_store_id_key").on(t.storeId, t.id),
  unique("order_completion_events_event_key").on(t.storeId, t.eventKey),
  foreignKey({ name: "order_completion_events_store_fk", columns: [t.storeId], foreignColumns: [storesTable.id] }).onDelete("restrict"),
  foreignKey({ name: "order_completion_events_order_fk", columns: [t.storeId, t.orderId], foreignColumns: [ordersTable.storeId, ordersTable.id] }).onDelete("restrict"),
  check("order_completion_events_from_status_valid", sql.raw("from_status IN ('pending','awaiting_payment','preparing','shipped','completed','cancelled')")),
  check("order_completion_events_to_status_valid", sql.raw("to_status IN ('pending','awaiting_payment','preparing','shipped','completed','cancelled')")),
  check("order_completion_events_transition_valid", sql.raw("from_status <> to_status AND (from_status = 'completed' OR to_status = 'completed')")),
  check("order_completion_events_completion_time", sql.raw("(to_status = 'completed' AND completed_at IS NOT NULL AND completed_at = occurred_at) OR (to_status <> 'completed' AND completed_at IS NULL)")),
]);
